BID_STATUS_PENDING_ENUM = 1
BID_STATUS_ACCEPTED_ENUM = 2
BID_STATUS_REJECTED_ENUM = 3
BID_STATUS_CANCELLED_ENUM = 4

BID_STATUS_PENDING = "Pending"
BID_STATUS_ACCEPTED = "Accepted"
BID_STATUS_REJECTED = "Rejected"
BID_STATUS_CANCELLED = "Cancelled"
