# Generated by Django 3.0.3 on 2021-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
