# Generated by Django 3.0.3 on 2021-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_creator_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
