# Generated by Django 3.0.3 on 2021-10-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20210930_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='participant_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
