# Generated by Django 3.0.3 on 2021-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_creator_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='slug',
            field=models.SlugField(default=''),
        )
    ]
