# Generated by Django 3.0.3 on 2021-11-02 12:14

from django.db import migrations
from crater.creator.services import generate_unique_slug_for_creator


def generate_unique_slugs(apps, schema_editor):
    Creator = apps.get_model('creator', 'Creator')
    creators = Creator.objects.all()

    for creator in creators:
        creator.slug = generate_unique_slug_for_creator(creator)
        creator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_creator_slug'),
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs)
    ]
