# Generated by Django 3.0.3 on 2021-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_auto_20211102_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
