# Generated by Django 3.0.3 on 2021-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_auto_20211102_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
