# Generated by Django 3.0.3 on 2021-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_auto_20211117_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='show_club_members',
            field=models.BooleanField(default=False),
        ),
    ]
