# Generated by Django 3.0.3 on 2021-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_creator_show_club_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coins_held',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='max_coins',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price',
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
