# Generated by Django 3.0.3 on 2021-12-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_creator_show_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
