# Generated by Django 3.0.3 on 2021-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_creator_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='creator/videos'),
        ),
    ]
