# Generated by Django 3.0.3 on 2021-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_auto_20211223_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='creator/videos/poster/'),
        ),
    ]
