# Generated by Django 3.0.3 on 2021-12-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_creator_video_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='number_of_subscribers',
            new_name='subscriber_count',
        ),
    ]
