# Generated by Django 3.0.3 on 2021-12-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_creator_video_poster'),
        ('creator', '0010_follower_notify'),
    ]

    operations = [
    ]
