# Generated by Django 3.0.3 on 2021-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0014_auto_20211229_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['-order']},
        ),
        migrations.AlterField(
            model_name='creator',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
