# Generated by Django 3.0.3 on 2022-01-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0014_merge_20211227_1836'),
        ('creator', '0015_auto_20211229_2002'),
    ]

    operations = [
    ]
