# Generated by Django 3.0.3 on 2022-01-16 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator', '0016_merge_20220103_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='point_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
