# Generated by Django 3.0.3 on 2022-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0016_merge_20220103_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='point_of_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
