# Generated by Django 3.0.3 on 2022-02-03 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator', '0017_creator_point_of_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('creator', 'user')},
        ),
    ]
