# Generated by Django 3.0.3 on 2022-02-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_auto_20220203_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='show_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
