# Generated by Django 3.0.3 on 2022-03-01 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator', '0019_creator_show_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='prospector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_prospector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creator',
            name='point_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_of_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
