# Generated by Django 3.0.3 on 2022-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0020_auto_20220301_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='tokens_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
