# Generated by Django 3.0.3 on 2022-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0021_creator_tokens_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='analytics_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
