# Generated by Django 3.0.3 on 2022-09-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0022_creator_analytics_enabled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorUPIInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('upi_id', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='creator/upi/qr_code')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_info', to='creator.Creator', verbose_name='Upi Info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
