# Generated by Django 3.0.3 on 2022-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0023_creatorupiinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='tokens_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
