LEADERBOARD_DURATION_WEEKLY_ENUM = 1
LEADERBOARD_DURATION_MONTHLY_ENUM = 2

LEADERBOARD_DURATION_WEEKLY = "Weekly"
LEADERBOARD_DURATION_MONTHLY = "Monthly"

LEADERBOARD_DURATION_CHOICES = (
    (LEADERBOARD_DURATION_WEEKLY_ENUM, LEADERBOARD_DURATION_WEEKLY),
    (LEADERBOARD_DURATION_MONTHLY_ENUM, LEADERBOARD_DURATION_MONTHLY)
)

DURATION_TYPE_TO_DAYS_MAP = {
    LEADERBOARD_DURATION_MONTHLY_ENUM: 30,
    LEADERBOARD_DURATION_WEEKLY_ENUM: 6
}
