# Generated by Django 3.0 on 2020-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_superuser',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
