# Generated by Django 3.0.2 on 2020-01-20 16:31

from django.db import migrations, models
import utils.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200114_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, storage=utils.storage_backends.PrivateMediaStorage(), upload_to='messages/%Y/%m/%d', verbose_name='File'),
        ),
    ]
