# Generated by Django 3.0.2 on 2020-01-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStarredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_stars', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Star',
                'verbose_name_plural': 'Chat Stars',
                'db_table': 'chat_stars',
                'unique_together': {('creator', 'user')},
            },
        ),
    ]
