# Generated by Django 3.0.3 on 2020-10-22 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_messageemailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageemailnotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_email_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageemailnotification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_email_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
