# Generated by Django 3.0.3 on 2021-05-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0024_meetingpreference_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyteMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dyte_meeting_id', models.CharField(max_length=128)),
                ('room_name', models.CharField(max_length=128)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dyte_meeting', to='meetings.Meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
