# Generated by Django 3.0.3 on 2021-10-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0003_auto_20210917_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyteMeetingRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recording_id', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('path', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('dyte_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_recording', to='dyte.DyteMeeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
