# Generated by Django 3.0.3 on 2021-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0004_dytemeetingrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='dytemeetingparticipant',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dytemeetingrecording',
            name='status',
            field=models.CharField(choices=[('INVOKED', 'INVOKED'), ('RECORDING', 'RECORDING'), ('UPLOADING', 'UPLOADING'), ('UPLOADED', 'UPLOADED'), ('ERRORED', 'ERRORED')], default='INVOKED', max_length=16),
        ),
    ]
