# Generated by Django 3.0.3 on 2021-12-27 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyte', '0005_auto_20211005_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dytemeetingparticipant',
            unique_together={('dyte_meeting', 'participant')},
        ),
    ]
