# Generated by Django 3.0.3 on 2022-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0006_auto_20211224_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='dytemeetingparticipant',
            name='minutes_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
