# Generated by Django 3.0.3 on 2022-04-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0007_dytemeetingparticipant_minutes_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyteParticipantOnlineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('online_at', models.DateTimeField(auto_now_add=True)),
                ('offline_at', models.DateTimeField(blank=True, null=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('dyte_meeting_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyte.DyteMeetingParticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
