# Generated by Django 3.0.3 on 2022-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0008_dyteparticipantonlinelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyteparticipantonlinelog',
            name='online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
