# Generated by Django 3.0.3 on 2022-08-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0009_auto_20220720_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyteparticipantonlinelog',
            name='dyte_meeting_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_logs', to='dyte.DyteMeetingParticipant'),
        ),
    ]
