# Generated by Django 3.0.3 on 2022-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0010_auto_20220811_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='dytemeetingrecording',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
