# Generated by Django 3.0.3 on 2022-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0011_dytemeetingrecording_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dytemeetingrecording',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
