# Generated by Django 3.0.3 on 2022-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0012_auto_20220903_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dytemeetingrecording',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='File Size(MB)'),
        ),
    ]
