# Generated by Django 3.0.3 on 2022-09-08 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0013_auto_20220905_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dytemeetingparticipant',
            name='minutes_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
