# Generated by Django 3.0.3 on 2022-09-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0014_auto_20220909_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OFFLINE', 'OFFLINE'), ('LIVE', 'LIVE')], default='OFFLINE', max_length=32)),
                ('ingest_seconds', models.IntegerField(default=0)),
                ('viewer_seconds', models.IntegerField(default=0)),
                ('ingest_server', models.CharField(max_length=512)),
                ('livestream_id', models.CharField(max_length=255)),
                ('stream_key', models.CharField(max_length=255)),
                ('playback_url', models.CharField(max_length=512)),
                ('dyte_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to='dyte.DyteMeeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
