# Generated by Django 3.0.3 on 2022-09-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0015_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='ingest_server',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='playback_url',
            field=models.TextField(),
        ),
    ]
