SALE_PAYMENT_PENDING_ENUM = 1
SALE_PAYMENT_CONFIRMED_ENUM = 2
SALE_PAYMENT_DECLINED_ENUM = 3

SALE_PAYMENT_PENDING = "Payment Pending"
SALE_PAYMENT_CONFIRMED = "Payment Confirmed"
SALE_PAYMENT_DECLINED = "Payment Declined"


SALE_PAYMENT_TYPE_UPI_ENUM = 1
SALE_PAYMENT_TYPE_LEARN_ENUM = 2

SALE_PAYMENT_TYPE_UPI = "Upi"
SALE_PAYMENT_TYPE_LEARN = "Learn"
