# Generated by Django 3.0.3 on 2022-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveIntegerField(choices=[(1, 'Stripe')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
        ),
    ]
