# Generated by Django 3.0.3 on 2022-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_payments', '0002_auto_20220225_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveIntegerField(choices=[(1, 'Stripe'), (2, 'Creator Upi')], default=1),
        ),
    ]
