version: "3"

services:

  db:
    container_name: freelance_db
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=freelance_pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SecurityPassword
    ports:
      - "5432:5432"

  redis:
    container_name: freelance_redis
    image: redis:5.0.7
    env_file: "./docker/environments"
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  app:
    container_name: freelance_app
    platform: linux/amd64
    entrypoint: ./bin/develop_entry_point.sh
    build:
      context: app
      args:
        requirements_file: requirements.dev.txt
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./docker:/docker
    env_file: "./docker/environments"
    environment:
      DJANGO_SETTINGS_MODULE: freelance.settings
      POSTGRES_HOST: "db"
    depends_on:
      - db
      - redis

  celery:
    container_name: freelance_celery
    platform: linux/amd64
    build:
      context: app
      args:
        requirements_file: requirements.dev.txt
    command: "celery -A freelance worker -l info --concurrency=4"
    env_file: "./docker/environments"
    environment:
      DJANGO_SETTINGS_MODULE: freelance.settings
      POSTGRES_HOST: "db"
    volumes:
      - ./app:/app
      - ./docker:/docker
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  celery-beat:
    container_name: freelance_celery_beat
    platform: linux/amd64
    build:
      context: app
      args:
        requirements_file: requirements.dev.txt
    command: "celery -A freelance beat -l debug --pidfile="
    env_file: "./docker/environments"
    environment:
      DJANGO_SETTINGS_MODULE: freelance.settings
      POSTGRES_HOST: "db"
    volumes:
      - ./app:/app
      - ./docker:/docker
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
