# Generated by Django 3.0.3 on 2022-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
