# Generated by Django 3.0.3 on 2022-08-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms_emails', '0002_auto_20220823_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='send_at',
            new_name='sent_at',
        ),
    ]
