# Generated by Django 3.0.3 on 2022-08-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms_emails', '0003_auto_20220823_2158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'service')},
        ),
    ]
