# Generated by Django 3.0.3 on 2021-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20210322_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='calculate_score',
            field=models.BooleanField(default=True),
        ),
    ]
