# Generated by Django 3.0.3 on 2021-04-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0007_auto_20210429_1554'),
        ('conversations', '0003_group_calculate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curated_articles.CuratedArticle'),
        ),
    ]
