# Generated by Django 3.0.3 on 2021-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20210503_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
