# Generated by Django 3.0.3 on 2021-06-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0006_group_is_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Topic',
                'verbose_name_plural': 'Suggested Topics',
                'ordering': ['-created_at'],
            },
        ),
    ]
