# Generated by Django 3.0.3 on 2021-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_suggestedtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
