# Generated by Django 3.0.3 on 2021-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_auto_20210629_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA')], default=0),
        ),
        migrations.AddField(
            model_name='suggestedtopic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA')], default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA')], default=0),
        ),
    ]
