# Generated by Django 3.0.3 on 2021-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_auto_20210702_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_type',
            field=models.PositiveIntegerField(choices=[(1, 'Speaker'), (2, 'Attendee')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA'), (2, 'Webinar')], default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA'), (2, 'Webinar')], default=0),
        ),
    ]
