# Generated by Django 3.0.3 on 2021-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_auto_20210913_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='type',
            field=models.IntegerField(choices=[('speaker', 'speaker'), (1, 'attendee')], default=0),
        ),
        migrations.AlterField(
            model_name='suggestedtopic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA'), (2, 2)], default=0),
        ),
    ]
