# Generated by Django 3.0.3 on 2021-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0026_auto_20210902_1656'),
        ('tags', '0018_sourcewebsite_is_active'),
        ('conversations', '0011_auto_20210916_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, to='meetings.Interest', verbose_name='Interests'),
        ),
    ]
