# Generated by Django 3.0.3 on 2021-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0026_auto_20210902_1656'),
        ('conversations', '0011_auto_20210916_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='calculate_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, to='meetings.Interest', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, to='conversations.Category', verbose_name='Categories'),
        ),
    ]
