# Generated by Django 3.0.3 on 2021-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_auto_20210922_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='calculate_score',
            field=models.BooleanField(default=False),
        ),
    ]
