# Generated by Django 3.0.3 on 2021-09-22 10:53

from django.db import migrations

LIST_OF_CATEGORIES = [
    "Marketing",
    "Branding",
    "Finance",
    "Career",
    "Content Creation",
    "Stocks",
    "Crypto",
    "Startups",
    "Design",
    "Coding"
]


def create_initial_category_data(apps, schema_editor):
    Category = apps.get_model("conversations", "Category")

    all_categories = []

    for category_name in LIST_OF_CATEGORIES:
        all_categories.append(Category(name=category_name))

    Category.objects.bulk_create(all_categories)


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_auto_20210922_1622'),
    ]

    operations = [
        migrations.RunPython(create_initial_category_data)
    ]
