# Generated by Django 3.0.3 on 2021-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_auto_20210922_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Enter color code for the color here.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/category/%Y/%m/%d/', verbose_name='Category Photo'),
        ),
    ]
