# Generated by Django 3.0.3 on 2021-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_auto_20210923_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
