# Generated by Django 3.0.3 on 2021-10-05 11:45

import conversations.models
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0005_auto_20211005_1530'),
        ('conversations', '0016_grouplivelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recording', models.FileField(null=True, upload_to=conversations.models.recording_storage_path, validators=[utils.validators.SizeValidator(size=512)])),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('dyte_recordings', models.ManyToManyField(blank=True, null=True, to='dyte.DyteMeetingRecording')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='conversations.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
