# Generated by Django 3.0.3 on 2021-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_grouplivelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
