# Generated by Django 3.0.3 on 2021-10-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0005_auto_20211005_1530'),
        ('conversations', '0017_grouprecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecording',
            name='dyte_recordings',
            field=models.ManyToManyField(to='dyte.DyteMeetingRecording'),
        ),
    ]
