# Generated by Django 3.0.3 on 2021-10-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_auto_20211006_1312'),
        ('conversations', '0018_auto_20211005_1733'),
    ]

    operations = [
    ]
