# Generated by Django 3.0.3 on 2021-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyte', '0005_auto_20211005_1530'),
        ('conversations', '0019_merge_20211006_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecording',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grouprecording',
            name='dyte_recordings',
            field=models.ManyToManyField(blank=True, to='dyte.DyteMeetingRecording'),
        ),
    ]
