# Generated by Django 3.0.3 on 2021-10-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_auto_20211013_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRtmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('link', models.TextField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rtmp', to='conversations.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
