# Generated by Django 3.0.3 on 2021-10-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0021_grouprtmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
