# Generated by Django 3.0.3 on 2021-10-21 12:02

from django.db import migrations


def make_groups_published(apps, schema_editor):
    group = apps.get_model('conversations', 'Group')
    group.objects.all().update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0022_group_is_published'),
    ]

    operations = [
        migrations.RunPython(make_groups_published),
    ]
