# Generated by Django 3.0.3 on 2021-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0025_auto_20211210_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatreaction',
            name='url',
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatreaction',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
