# Generated by Django 3.0.3 on 2021-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0025_auto_20211215_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatreaction',
            name='file',
            field=models.FileField(upload_to='reactions/gifs'),
        ),
        migrations.AlterField(
            model_name='chatreaction',
            name='image',
            field=models.ImageField(upload_to='reactions/icons'),
        ),
    ]
