# Generated by Django 3.0.3 on 2022-01-25 10:59

import conversations.models
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0026_auto_20211216_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecording',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=conversations.models.recording_storage_path, validators=[utils.validators.SizeValidator(size=512)]),
        ),
    ]
