# Generated by Django 3.0.3 on 2021-12-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0027_auto_20211210_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
