# Generated by Django 3.0.3 on 2022-01-31 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0027_auto_20220125_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, to='conversations.Category', verbose_name='Categories')),
                ('groups', models.ManyToManyField(related_name='series_groups', to='conversations.Group', verbose_name='Groups')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_hosted', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_topic', to='conversations.Topic')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at'],
            },
        ),
    ]
