# Generated by Django 3.0.3 on 2022-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0028_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprecording',
            name='order',
        ),
    ]
