# Generated by Django 3.0.3 on 2022-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0029_remove_grouprecording_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
