# Generated by Django 3.0.3 on 2022-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0030_series_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='firebase_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
