# Generated by Django 3.0.3 on 2022-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0031_groupmessage_firebase_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
