# Generated by Django 3.0.3 on 2022-03-21 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0031_groupmessage_firebase_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='groups/category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Category Photo'),
        ),
    ]
