# Generated by Django 3.0.3 on 2022-03-19 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0032_category_show_on_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='groups/category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Category Photo'),
        ),
    ]
