# Generated by Django 3.0.3 on 2022-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0032_auto_20220321_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_obs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
