# Generated by Django 3.0.3 on 2022-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0033_auto_20220324_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_minutes_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
