# Generated by Django 3.0.3 on 2022-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0033_auto_20220324_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecording',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
