# Generated by Django 3.0.3 on 2022-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0034_group_total_minutes_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='total_minutes_spent',
            new_name='total_minutes_spent_by_attendees',
        ),
        migrations.AddField(
            model_name='group',
            name='total_minutes_spent_by_host',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
