# Generated by Django 3.0.3 on 2022-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0035_auto_20220408_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecording',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
