# Generated by Django 3.0.3 on 2022-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0036_grouprecording_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'text'), (2, 'reaction'), (3, 'action')], default=1),
        ),
    ]
