# Generated by Django 3.0.3 on 2022-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0038_groupquestion_questionupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA'), (2, 'Webinar')], default=2),
        ),
    ]
