# Generated by Django 3.0.3 on 2022-07-19 07:59

import conversations.models
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0040_auto_20220629_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecording',
            name='recording',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=conversations.models.recording_storage_path, validators=[utils.validators.SizeValidator(size=1024)]),
        ),
    ]
