# Generated by Django 3.0.3 on 2022-07-12 10:45

from django.db import migrations
from conversations.private import generate_unique_slug_for_category


def generate_unique_slugs(apps, schema_editor):
    Category = apps.get_model('conversations', 'Category')
    categories = Category.objects.all()

    for category in categories:
        category.slug = generate_unique_slug_for_category(category)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0041_category_slug'),
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs)
    ]
