# Generated by Django 3.0.3 on 2022-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0044_auto_20220719_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
