# Generated by Django 3.0.3 on 2022-08-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0045_group_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='medium',
            field=models.IntegerField(choices=[(0, 'audio'), (1, 'audio & video')], default=1),
        ),
    ]
