# Generated by Django 3.0.3 on 2022-09-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0046_auto_20220825_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
