# Generated by Django 3.0.3 on 2022-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0047_auto_20220914_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enable_stream_on_start',
            field=models.BooleanField(default=False),
        ),
    ]
