# Generated by Django 3.0.3 on 2022-10-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0048_group_enable_stream_on_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedtopic',
            old_name='is_approved',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='suggestedtopic',
            name='suggested_by',
        ),
        migrations.AddField(
            model_name='suggestedtopic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_topic', to='conversations.Category'),
        ),
        migrations.AddField(
            model_name='suggestedtopic',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedtopic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Generic Group'), (1, 'AMA'), (2, 'Webinar')], default=2),
        ),
    ]
