# Generated by Django 3.0.3 on 2022-10-15 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0050_auto_20221011_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupupvote',
            unique_together={('group', 'user')},
        ),
    ]
