# Generated by Django 3.0.3 on 2022-10-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0051_auto_20221015_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='session_active',
            field=models.BooleanField(default=False, help_text="Denotes if group active on Dyte's end.", verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enable_stream_on_start',
            field=models.BooleanField(default=False, verbose_name='Enable HLS'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Live'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_obs',
            field=models.BooleanField(default=False, verbose_name='OBS'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_rescheduled',
            field=models.BooleanField(default=False, verbose_name='Rescheduled'),
        ),
    ]
