USER_TYPE_ATTENDEE = "attendee"
USER_TYPE_STREAMER = "streamer"

USER_TYPE_ATTENDEE_ENUM = 1
USER_TYPE_STREAMER_ENUM = 2


TRANSACTION_TYPE_ACQUIRED = "acquired"
TRANSACTION_TYPE_REDEEMED = "redeemed"

TRANSACTION_TYPE_ACQUIRED_ENUM = 1
TRANSACTION_TYPE_REDEEMED_ENUM = 2

EXTRA_WATCH_TIME_FOR_CREATOR_PER_STREAM = 1000
