from django.utils.regex_helper import Choice
from django.utils.translation import ugettext_lazy as _

REASON_CHOICES = (
    ('18_year_old', _('I am at least 18 year old.')),
    ('join', _('I want to join the community to collaborate or share.')),
    ('understand', _('I understand the membership application process.')),
    ('can_verify_bank_account', _('I can verify a bank account & government-issued ID')),
    ('have_a_debit', _('I have a debit &/ or credit card')),
    ('investor_in_companies', _('I am qualified to sign up as an investor in companies')),
    (
        'connectionsare',
        _('I understand that no from of trading of equities take place on the platform, only connectionsare made')
    )
)

USER_GROUP = 'User'
INVESTOR_GROUP = 'Investor'

INTENT_NETWORK = 'network'
INTENT_SERVICES = 'services'

INTENT_CHOICES = (
    (INTENT_NETWORK, INTENT_NETWORK.title()),
    (INTENT_SERVICES, INTENT_SERVICES.title())
)

template_names = {
    'password_reset': 'Password Reset New',
    'verify_email': 'Verify email',
    'invite_friend': 'Invite Friend',
    'participate_event': 'Participate in Event',
    'two_weeks_subs_warning': 'Two weeks subs warning',
    'one_month_subs_warning': 'One month subs warning'
}

DEFAULT_LINKED_IN_URL = 'https://www.no-information.com/'

ADMIN_USER_EMAIL = 'admin@admin.com'

OS_NAME_ANDROID = 'ANDROID'
OS_NAME_IOS = 'IOS'
OS_NAME_WEB = 'WEB'

DEVICE_NAME_OTHER = 'Other'
DEVICE_NAME_WEB = 'WEB'

PASSWORD_RESET_FROM_EMAIL = "set-password@worknetwork.in"

# Source constants.
BASE_SOURCE_FACEBOOK = "Facebook"
BASE_SOURCE_LINKEDIN = "Linkedin"
BASE_SOURCE_BUMBLE = "Bumble"
BASE_SOURCE_GOOGLE = "Google"
BASE_SOURCE_REFERRAL = "Referral"
BASE_SOURCE_ORGANIC = "Organic"
BASE_SOURCE_KODO = "Kodo"

BASE_SOURCE_TO_SCORE_MAP = {
    BASE_SOURCE_FACEBOOK: 50,
    BASE_SOURCE_LINKEDIN: 100,
    BASE_SOURCE_REFERRAL: 80,
    BASE_SOURCE_BUMBLE: 70,
    BASE_SOURCE_ORGANIC: 50,
    BASE_SOURCE_GOOGLE: 70
}

TYPEFORM_URL_TO_SOURCE_MAP = {
    "https://worknetwork.typeform.com/to/H8wMoIyV": ("Linkedin", "Linkedin Women"),
    "https://worknetwork.typeform.com/to/oh1lVxPJ": ("Linkedin", "Linkedin Helper(Yash)"),
    "https://worknetwork.typeform.com/to/LorqbZPS": ("Linkedin", "Linkedin Helper(Keziah)"),
    "https://worknetwork.typeform.com/to/ltoxdMaX": ("Linkedin", "Linkedin Manual"),
    "https://worknetwork.typeform.com/to/Xdvnp8bO": ("Bumble", "Bumble Bizz"),
    "https://worknetwork.typeform.com/to/CN4xKZL8": ("Facebook", "Facebook: F2 Direct to TF"),
    "https://worknetwork.typeform.com/to/MNbvcw7y": ("Facebook", "Facebook: F1 Landing page to TF"),
    "https://worknetwork.typeform.com/to/YbWuCTJy": ("Facebook", "Facebook: Exp Funnel"),
    "https://worknetwork.typeform.com/to/l3uR33Zv": ("Facebook", "Facebook: F1 Landing page to TF (Not Active)"),
    "https://worknetwork.typeform.com/to/oTCMwo9P": ("Google", "Google Ads: Landing Page to TF")
}

EXISTING_SOURCES_TO_NEW_SOURCE_MAP = {
    "MF1: LP_TF": ("Facebook", "Facebook: F1 Landing page to TF"),
    "MF2: D_TF": ("Facebook", "Facebook: F2 Direct to TF"),
    "MF3: LI_OR": ("Linkedin", "Linkedin Manual"),
    "F2 - TYPEFORM": ("Facebook", "Facebook: F2 Direct to TF"),
    "F2-TYPEFORM": ("Facebook", "Facebook: F2 Direct to TF"),
    "typeform": ("Facebook", "Facebook: F1 Landing page to TF"),
    "https://worknetwork.typeform.com/to/H8wMoIyV": ("Linkedin", "Linkedin Women"),
    "https://worknetwork.typeform.com/to/oh1lVxPJ": ("Linkedin", "Linkedin Helper(Yash)"),
    "https://worknetwork.typeform.com/to/LorqbZPS": ("Linkedin", "Linkedin Helper(Keziah)"),
    "https://worknetwork.typeform.com/to/ltoxdMaX": ("Linkedin", "Linkedin Manual"),
    "https://worknetwork.typeform.com/to/Xdvnp8bO": ("Bumble", "Bumble Bizz"),
    "https://worknetwork.typeform.com/to/CN4xKZL8": ("Facebook", "Facebook: F2 Direct to TF"),
    "https://worknetwork.typeform.com/to/MNbvcw7y": ("Facebook", "Facebook: F1 Landing page to TF"),
    "https://worknetwork.typeform.com/to/YbWuCTJy": ("Facebook", "Facebook: Exp Funnel"),
    "https://worknetwork.typeform.com/to/l3uR33Zv": ("Facebook", "Facebook: F1 Landing page to TF (Not Active)"),
    "https://worknetwork.typeform.com/to/oTCMwo9P": ("Google", "Google Ads: Landing Page to TF")
}

# Education level constants.
EDUCATION_LEVEL_HIGH_SCHOOL = "High School"
EDUCATION_LEVEL_UNDERGRADUATE = "Undergraduate"
EDUCATION_LEVEL_MASTERS = "Masters"
EDUCATION_LEVEL_MBA = "MBA"
EDUCATION_LEVEL_PHD = "PhD"

EDUCATION_LEVEL_HIGH_SCHOOL_ENUM = 1
EDUCATION_LEVEL_UNDERGRADUATE_ENUM = 2
EDUCATION_LEVEL_MASTERS_ENUM = 3
EDUCATION_LEVEL_MBA_ENUM = 4
EDUCATION_LEVEL_PHD_ENUM = 5

EDUCATION_LEVEL_STR_TO_ENUM = {
    EDUCATION_LEVEL_HIGH_SCHOOL: EDUCATION_LEVEL_HIGH_SCHOOL_ENUM,
    EDUCATION_LEVEL_UNDERGRADUATE: EDUCATION_LEVEL_UNDERGRADUATE_ENUM,
    EDUCATION_LEVEL_MASTERS: EDUCATION_LEVEL_MASTERS_ENUM,
    EDUCATION_LEVEL_MBA: EDUCATION_LEVEL_MBA_ENUM,
    EDUCATION_LEVEL_PHD: EDUCATION_LEVEL_PHD_ENUM
}

# Years of experience constants.
EXPERIENCE_ONE_TO_TWO_YEARS = "0 - 2 years"
EXPERIENCE_THREE_TO_FIVE_YEARS = "3 - 5 years"
EXPERIENCE_SIX_TO_TEN_YEARS = "6 - 10 years"
EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS = "11 - 15 years"
EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS = "16 - 20 years"
EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS = "21 - 30 years"
EXPERIENCE_THIRTY_PLUS_YEARS = "30+ years"

EXPERIENCE_ONE_TO_TWO_YEARS_ENUM = 1
EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM = 2
EXPERIENCE_SIX_TO_TEN_YEARS_ENUM = 3
EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM = 4
EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM = 5
EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM = 6
EXPERIENCE_THIRTY_PLUS_YEARS_ENUM = 7

EXPERIENCE_STR_TO_ENUM = {
    EXPERIENCE_ONE_TO_TWO_YEARS: EXPERIENCE_ONE_TO_TWO_YEARS_ENUM,
    EXPERIENCE_THREE_TO_FIVE_YEARS: EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM,
    EXPERIENCE_SIX_TO_TEN_YEARS: EXPERIENCE_SIX_TO_TEN_YEARS_ENUM,
    EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS: EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM,
    EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS: EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM,
    EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS: EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM,
    EXPERIENCE_THIRTY_PLUS_YEARS: EXPERIENCE_THIRTY_PLUS_YEARS_ENUM
}

# Company type constants.
COMPANY_TYPE_NOT_EMPLOYED = "Not Employed"
COMPANY_TYPES_START_UP = "Startup"
COMPANY_TYPE_MNC = "MNC"
COMPANY_TYPE_SME = "SME"
COMPANY_TYPE_CONSULTANCY = "Consultancy"
COMPANY_TYPE_FUND = "Fund"
COMPANY_TYPE_FREELANCE = "Freelance"

COMPANY_TYPE_NOT_EMPLOYED_ENUM = 1
COMPANY_TYPES_START_UP_ENUM = 2
COMPANY_TYPE_MNC_ENUM = 3
COMPANY_TYPE_SME_ENUM = 4
COMPANY_TYPE_CONSULTANCY_ENUM = 5
COMPANY_TYPE_FUND_ENUM = 6
COMPANY_TYPE_FREELANCE_ENUM = 7

COMPANY_TYPE_STR_ENUM = {
    COMPANY_TYPE_NOT_EMPLOYED: COMPANY_TYPE_NOT_EMPLOYED_ENUM,
    COMPANY_TYPES_START_UP: COMPANY_TYPES_START_UP_ENUM,
    COMPANY_TYPE_MNC: COMPANY_TYPE_MNC_ENUM,
    COMPANY_TYPE_SME: COMPANY_TYPE_SME_ENUM,
    COMPANY_TYPE_CONSULTANCY: COMPANY_TYPE_CONSULTANCY_ENUM,
    COMPANY_TYPE_FUND: COMPANY_TYPE_FUND_ENUM,
    COMPANY_TYPE_FREELANCE: COMPANY_TYPE_FREELANCE_ENUM,
}

# Sector constants.
SECTOR_TYPE_ADVISORY_CONSULTANCY = "Advisory & Consultancy"
SECTOR_TYPE_AGRICULTURE = "Agriculture"
SECTOR_TYPE_AI_ML_BLOCKCHAIN = "AI/ML/Blockchain"
SECTOR_TYPE_AIRLINE_AVIATION = "Airline/Aviation"
SECTOR_TYPE_APPAREL_FASHION = "Apparel & Fashion"
SECTOR_TYPE_AUTOMOTIVE_TRANSPORTATION = "Automotive & Transportation"
SECTOR_TYPE_CIVIC_SOCIAL = "Civic & Social Organization"
SECTOR_TYPE_CONSUMER_SERVICES = "Consumer Services"
SECTOR_TYPE_COSMETICS = "Cosmetics"
SECTOR_TYPE_DESIGN_MEDIA = "Design & Media"
SECTOR_TYPE_ECOMMERCE = "E-commerce"
SECTOR_TYPE_EDUCATION = "Education"
SECTOR_TYPE_ENTERTAINMENT = "Entertainment"
SECTOR_TYPE_OFFLINE = "Offline Events"
SECTOR_TYPE_FINANCE = "Financial Services"
SECTOR_TYPE_FOOD_BEVERAGE = "Food & Beverage"
SECTOR_TYPE_GAMING = "Gaming"
SECTOR_TYPE_HEALTH_WELLNESS = "Health, Wellness & Fitness"
SECTOR_TYPE_HOSPITALITY = "Hospitality"
SECTOR_TYPE_IT = "Information technology & Services"
SECTOR_TYPE_INVESTMENT_CAPITAL = "Investment Management  & Capital Markets"
SECTOR_TYPE_LEGAL = "Legal sector"
SECTOR_TYPE_LEISURE_TRAVEL_TOURISM = "Leisure Travel & Tourism"
SECTOR_TYPE_LUXURY_CONSUMER_GOODS = "Luxury & Consumer Goods"
SECTOR_TYPE_MARKETING_ADVERTING = "Marketing & Adverting"
SECTOR_TYPE_PACKAGING_DISTRIBUTION = "Packaging & Distribution"
SECTOR_TYPE_PHARMA = "Pharmaceutical"
SECTOR_TYPE_PHILANTHROPY = "Philanthropy"
SECTOR_TYPE_REAL_ESTATE = "Real Estate"
SECTOR_TYPE_RENEWABLE_ENVIRONMENT = "Renewables & Environment"
SECTOR_TYPE_SPORTS = "Sports"
SECTOR_TYPE_STAFFING_AND_RECRUITING = "Staffing & Recruiting"
SECTOR_TYPE_COMMUNITY_SOCIAL = "Community & Social"
SECTOR_TYPE_TECHNOLOGY_INTERNET_SOFTWARE = "Technology,  Internet  & Software"
SECTOR_TYPE_CIVIL_MECHANICAL_ELECTRICAL = "Civil, Mechanical or Electrical Engineering"
SECTOR_TYPE_LOGISTICS = "Logistics"
SECTOR_TYPE_OTHER = "Other"

SECTOR_TYPE_ADVISORY_CONSULTANCY_ENUM = 1
SECTOR_TYPE_AGRICULTURE_ENUM = 2
SECTOR_TYPE_AI_ML_BLOCKCHAIN_ENUM = 3
SECTOR_TYPE_AIRLINE_AVIATION_ENUM = 4
SECTOR_TYPE_APPAREL_FASHION_ENUM = 5
SECTOR_TYPE_AUTOMOTIVE_TRANSPORTATION_ENUM = 6
SECTOR_TYPE_CIVIC_SOCIAL_ENUM = 7
SECTOR_TYPE_CONSUMER_SERVICES_ENUM = 8
SECTOR_TYPE_COSMETICS_ENUM = 9
SECTOR_TYPE_DESIGN_MEDIA_ENUM = 10
SECTOR_TYPE_ECOMMERCE_ENUM = 11
SECTOR_TYPE_EDUCATION_ENUM = 12
SECTOR_TYPE_ENTERTAINMENT_ENUM = 13
SECTOR_TYPE_OFFLINE_ENUM = 14
SECTOR_TYPE_FINANCE_ENUM = 15
SECTOR_TYPE_FOOD_BEVERAGE_ENUM = 16
SECTOR_TYPE_GAMING_ENUM = 17
SECTOR_TYPE_HEALTH_WELLNESS_ENUM = 18
SECTOR_TYPE_HOSPITALITY_ENUM = 19
SECTOR_TYPE_IT_ENUM = 20
SECTOR_TYPE_INVESTMENT_CAPITAL_ENUM = 21
SECTOR_TYPE_LEGAL_ENUM = 22
SECTOR_TYPE_LEISURE_TRAVEL_TOURISM_ENUM = 23
SECTOR_TYPE_LUXURY_CONSUMER_GOODS_ENUM = 24
SECTOR_TYPE_MARKETING_ADVERTING_ENUM = 25
SECTOR_TYPE_PACKAGING_DISTRIBUTION_ENUM = 26
SECTOR_TYPE_PHARMA_ENUM = 27
SECTOR_TYPE_PHILANTHROPY_ENUM = 28
SECTOR_TYPE_REAL_ESTATE_ENUM = 29
SECTOR_TYPE_RENEWABLE_ENVIRONMENT_ENUM = 30
SECTOR_TYPE_SPORTS_ENUM = 31
SECTOR_TYPE_STAFFING_AND_RECRUITING_ENUM = 32
SECTOR_TYPE_COMMUNITY_SOCIAL_ENUM = 33
SECTOR_TYPE_TECHNOLOGY_INTERNET_SOFTWARE_ENUM = 34
SECTOR_TYPE_CIVIL_MECHANICAL_ELECTRICAL_ENUM = 35
SECTOR_TYPE_LOGISTICS_ENUM = 36
SECTOR_TYPE_OTHER_ENUM = 60

SECTOR_TYPE_STR_TO_ENUM = {
    SECTOR_TYPE_ADVISORY_CONSULTANCY: SECTOR_TYPE_ADVISORY_CONSULTANCY_ENUM,
    SECTOR_TYPE_AGRICULTURE: SECTOR_TYPE_AGRICULTURE_ENUM,
    SECTOR_TYPE_AI_ML_BLOCKCHAIN: SECTOR_TYPE_AI_ML_BLOCKCHAIN_ENUM,
    SECTOR_TYPE_AIRLINE_AVIATION: SECTOR_TYPE_AIRLINE_AVIATION_ENUM,
    SECTOR_TYPE_APPAREL_FASHION: SECTOR_TYPE_APPAREL_FASHION_ENUM,
    SECTOR_TYPE_AUTOMOTIVE_TRANSPORTATION: SECTOR_TYPE_AUTOMOTIVE_TRANSPORTATION_ENUM,
    SECTOR_TYPE_CIVIC_SOCIAL: SECTOR_TYPE_CIVIC_SOCIAL_ENUM,
    SECTOR_TYPE_CONSUMER_SERVICES: SECTOR_TYPE_CONSUMER_SERVICES_ENUM,
    SECTOR_TYPE_COSMETICS: SECTOR_TYPE_COSMETICS_ENUM,
    SECTOR_TYPE_DESIGN_MEDIA: SECTOR_TYPE_DESIGN_MEDIA_ENUM,
    SECTOR_TYPE_ECOMMERCE: SECTOR_TYPE_ECOMMERCE_ENUM,
    SECTOR_TYPE_EDUCATION: SECTOR_TYPE_EDUCATION_ENUM,
    SECTOR_TYPE_ENTERTAINMENT: SECTOR_TYPE_ENTERTAINMENT_ENUM,
    SECTOR_TYPE_OFFLINE: SECTOR_TYPE_OFFLINE_ENUM,
    SECTOR_TYPE_FINANCE: SECTOR_TYPE_FINANCE_ENUM,
    SECTOR_TYPE_FOOD_BEVERAGE: SECTOR_TYPE_FOOD_BEVERAGE_ENUM,
    SECTOR_TYPE_GAMING: SECTOR_TYPE_GAMING_ENUM,
    SECTOR_TYPE_HEALTH_WELLNESS: SECTOR_TYPE_HEALTH_WELLNESS_ENUM,
    SECTOR_TYPE_HOSPITALITY: SECTOR_TYPE_HOSPITALITY_ENUM,
    SECTOR_TYPE_IT: SECTOR_TYPE_IT_ENUM,
    SECTOR_TYPE_INVESTMENT_CAPITAL: SECTOR_TYPE_INVESTMENT_CAPITAL_ENUM,
    SECTOR_TYPE_LEGAL: SECTOR_TYPE_LEGAL_ENUM,
    SECTOR_TYPE_LEISURE_TRAVEL_TOURISM: SECTOR_TYPE_LEISURE_TRAVEL_TOURISM_ENUM,
    SECTOR_TYPE_LUXURY_CONSUMER_GOODS: SECTOR_TYPE_LUXURY_CONSUMER_GOODS_ENUM,
    SECTOR_TYPE_MARKETING_ADVERTING: SECTOR_TYPE_MARKETING_ADVERTING_ENUM,
    SECTOR_TYPE_PACKAGING_DISTRIBUTION: SECTOR_TYPE_PACKAGING_DISTRIBUTION_ENUM,
    SECTOR_TYPE_PHARMA: SECTOR_TYPE_PHARMA_ENUM,
    SECTOR_TYPE_PHILANTHROPY: SECTOR_TYPE_PHILANTHROPY_ENUM,
    SECTOR_TYPE_REAL_ESTATE: SECTOR_TYPE_REAL_ESTATE_ENUM,
    SECTOR_TYPE_RENEWABLE_ENVIRONMENT: SECTOR_TYPE_RENEWABLE_ENVIRONMENT_ENUM,
    SECTOR_TYPE_SPORTS: SECTOR_TYPE_SPORTS_ENUM,
    SECTOR_TYPE_STAFFING_AND_RECRUITING: SECTOR_TYPE_STAFFING_AND_RECRUITING_ENUM,
    SECTOR_TYPE_COMMUNITY_SOCIAL: SECTOR_TYPE_COMMUNITY_SOCIAL_ENUM,
    SECTOR_TYPE_TECHNOLOGY_INTERNET_SOFTWARE: SECTOR_TYPE_TECHNOLOGY_INTERNET_SOFTWARE_ENUM,
    SECTOR_TYPE_CIVIL_MECHANICAL_ELECTRICAL: SECTOR_TYPE_CIVIL_MECHANICAL_ELECTRICAL_ENUM,
    SECTOR_TYPE_LOGISTICS: SECTOR_TYPE_LOGISTICS_ENUM,
    SECTOR_TYPE_OTHER: SECTOR_TYPE_OTHER_ENUM,
}

NUMBER_OF_EMPLOYEE_UPTO_10_ENUM = 1
NUMBER_OF_EMPLOYEE_UPTO_50_ENUM = 2
NUMBER_OF_EMPLOYEE_UPTO_100_ENUM = 3
NUMBER_OF_EMPLOYEE_UPTO_500_ENUM = 4
NUMBER_OF_EMPLOYEE_500_PLUS_ENUM = 5

NUMBER_OF_EMPLOYEE_UPTO_10 = "1-10"
NUMBER_OF_EMPLOYEE_UPTO_50 = "10-50"
NUMBER_OF_EMPLOYEE_UPTO_100 = "50-100"
NUMBER_OF_EMPLOYEE_UPTO_500 = "100-500"
NUMBER_OF_EMPLOYEE_500_PLUS = "500+"


PROJECT_TYPE_MARKETING_ENUM = 1
PROJECT_TYPE_GRAPHIC_DESIGN_ENUM = 2
PROJECT_TYPE_VIDEOGRAPHY_ENUM = 3
PROJECT_TYPE_UI_UX_ENUM = 4
PROJECT_TYPE_SOFTWARE_DEV_ENUM = 5

PROJECT_TYPE_MARKETING = "Marketing"
PROJECT_TYPE_GRAPHIC_DESIGN = "Graphic Design"
PROJECT_TYPE_VIDEOGRAPHY = "Videography"
PROJECT_TYPE_UI_UX = "UI/UX design"
PROJECT_TYPE_SOFTWARE_DEV = "Software development"

STAGE_OF_COMPANY_BOOTSTRAPPED_ENUM = 1
STAGE_OF_COMPANY_SEED_ENUM = 2
STAGE_OF_COMPANY_SERIES_A_ENUM = 3
STAGE_OF_COMPANY_SERIES_B_ENUM = 4
STAGE_OF_COMPANY_SERIES_C_ENUM = 5
STAGE_OF_COMPANY_SERIES_D_PLUS_ENUM = 6

STAGE_OF_COMPANY_BOOTSTRAPPED = "Bootstrapped"
STAGE_OF_COMPANY_SEED = "Seed Stage"
STAGE_OF_COMPANY_SERIES_A = "Series A"
STAGE_OF_COMPANY_SERIES_B = "Series B"
STAGE_OF_COMPANY_SERIES_C = "Series C"
STAGE_OF_COMPANY_SERIES_D_PLUS = "Series D+"

ASPIRATION_FOUNDER_ENUM = 1
ASPIRATION_FINANCIAL_EXPERT_ENUM = 2
ASPIRATION_LAWYER_ENUM = 3
ASPIRATION_SME_OWNER_ENUM = 4
ASPIRATION_MARKETING_ENUM = 5
ASPIRATION_DESIGNER_ENUM = 6
ASPIRATION_BUISNESS_ADVISOR_ENUM = 7
ASPIRATION_ENGINEER_ENUM = 8
ASPIRATION_PM_ENUM = 9
ASPIRATION_BD_ENUM = 10
ASPIRATION_INVESTOR_ENUM = 11
ASPIRATION_HR_ENUM = 12

ASPIRATION_FOUNDER = "Startup founder"
ASPIRATION_FINANCIAL_EXPERT = "Financial expert"
ASPIRATION_LAWYER = "Lawyer"
ASPIRATION_SME_OWNER = "SME owner"
ASPIRATION_MARKETING = "Marketing expert"
ASPIRATION_DESIGNER = "Designer"
ASPIRATION_BUISNESS_ADVISOR = "Business Advisor"
ASPIRATION_ENGINEER = "Engineer"
ASPIRATION_PM = "Product manager"
ASPIRATION_BD = "Business development executive"
ASPIRATION_INVESTOR = "Investor"
ASPIRATION_HR = "Hr executive"

DEFAULT_INTRODUCTION_STR = "{first_name} | {tag} | {experience} years experience | {sector} sector | Received a {education} degree | {conversation_str} on WorkNetwork"
