"""
Django settings for freelance project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import conversations
import datetime
import os
import sentry_sdk

from django.utils.translation import ugettext_lazy as _
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.dirname(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
FERNET_KEY = b'TwTXqQABy11_Sf_LlnmVZV3vX3zyg_n4vb5dZz64bX8='
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_REGEX_WHITELIST = [
    r"^http://localhost[:0-9]*",
    r"scenario-projects.com*",
    r"https://[a-zA-Z-]+.scenario-projects.com*",
    r"^https://localhost[:0-9]*",
    r"https://[a-zA-Z-]+.1worknetwork.com*",
    r"https://[a-zA-Z-]+.worknetwork.in*",
    r"https://worknetwork.in*",
    # r"^http://*",
]

EMAIL_BACKEND = "djrill.mail.backends.djrill.DjrillBackend"

AUTH_USER_MODEL = 'users.User'
import django.core.mail.backends.smtp
# Application definition

INSTALLED_APPS = [
    'channels',
    'consumers.chat',
    'material.admin',
    'material.admin.default',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'debug_toolbar',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'users.appleid',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth.registration',
    'rest_auth',
    'django_cleanup.apps.CleanupConfig',
    'drf_yasg',
    'timezone_field',
    'phonenumber_field',
    'corsheaders',
    'djrill',
    'adminsortable2',
    'filefield_cache',
    'django_user_agents',
    'colorfield',

    'base',
    'users',
    'locations',
    'tags',
    'community.groups',
    'community.comments',
    'community.posts',
    'integrations.freshchat',
    'integrations.google',
    'integrations.superpro',
    'integrations.agora',
    'resources.events',
    'resources.curated_articles',
    'resources.masterclasses',
    'resources.meetings',
    'rewards',
    'payment',
    'points',
    'wn_analytics',
    'services',
    'order',
    'creative_exchange',
    'notifications',
    'dashboard',
    'matching',
    'conversations',
]

SITE_ID = 1

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: os.environ.get('SHOW_TOOLBAR_CALLBACK'),
}

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
REST_USE_JWT = True

DEFAULT_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'users.authentication.JSONWebTokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DATETIME_FORMAT': DEFAULT_DATETIME_FORMAT,
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=30),
    'JWT_GET_USER_SECRET_KEY': 'utils.user_secret_key.get_user_secret_key',
    # 'JWT_PAYLOAD_HANDLER': 'utils.user_secret_key.jwt_payload_handler'
}

ASGI_APPLICATION = 'freelance.routing.application'
DJANGO_ALLOW_ASYNC_UNSAFE = True

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],
        },
    },
}

MATERIAL_ADMIN_SITE = {
    'HEADER':  _('Administration'),
    'TITLE':  _('Marketplace'),
    'FAVICON':  'admin/favicon.ico',
    'MAIN_BG_COLOR':  '#41adda',
    'MAIN_HOVER_COLOR':  '#747777',
    'PROFILE_PICTURE':  'admin/logo.jpg',
    'PROFILE_BG':  'admin/profile_bg.png',
    'LOGIN_LOGO':  'admin/logo.jpg',
    'LOGOUT_BG':  'admin/logout_bg.png',
    'REVERSE_TRAY': True,
    'APP_ICONS': {
        'authtoken': 'vpn_key',
        'account': 'account_box',
        'socialaccount': 'touch_app'
    },
    'MODEL_ICONS': {
        'token': 'vpn_key',
        'emailaddress': 'email',
        'socialaccount': 'device_hub',
        'socialtoken': 'vpn_key',
        'socialapp': 'settings_applications',
    }
}

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware'
]

ROOT_URLCONF = 'freelance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'freelance.context_processors.notifications.unread_messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freelance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DBNAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASS'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
        'default-character-set': 'utf8'
    },
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
]

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Calcutta'
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_CUSTOM_DOMAIN = None

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME:
    AWS_DEFAULT_ACL = None
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-central-1')
    AWS_TRANSCODER_REGION_NAME = os.getenv('AWS_TRASCODER_REGION_NAME')
    if not AWS_TRANSCODER_REGION_NAME:
        AWS_TRANSCODER_REGION_NAME = AWS_S3_REGION_NAME
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    STATICFILES_STORAGE = 'utils.storage_backends.StaticStorage'
    PUBLIC_MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'utils.storage_backends.PublicMediaStorage'
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(ROOT_DIR, "staticfiles")
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(ROOT_DIR, "media")
    AWS_TRANSCODER_REGION_NAME=''

REDIS_HOST = os.getenv('REDIS_HOST', 'freelance_redis')
CELERY_BROKER_URL = 'redis://%s:6379' % REDIS_HOST
CELERY_RESULT_BACKEND = 'redis://%s:6379' % REDIS_HOST
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'users.serializers.LoginSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserDetailSerializer',
    'PASSWORD_CHANGE_SERIALIZER': 'users.serializers.PasswordChangeSerializer',
    'PASSWORD_RESET_SERIALIZER': 'users.serializers.PasswordResetSerializer',
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'users.serializers.PasswordResetConfirmSerializer'
}
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'users.serializers.RegisterSerializer'
}

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        "api_key": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    'DOC_EXPANSION': 'none',
    'TAGS_SORTER': 'alpha'
}

OLD_PASSWORD_FIELD_ENABLED = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MANDRILL_API_KEY = os.getenv('MANDRILL_API_KEY', 'pAoVah9eVDu70a2yxajeBg')
# Using because Mandrill sends error if it can't send emails because of various
# user side reasons. We don't these error since we can't do anything about them.
MANDRILL_IGNORE_RECIPIENT_STATUS = True
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@fwmail.scenario-projects.com')


DEFAULT_SMS_PHONE_NUMBER = os.getenv('DEFAULT_SMS_PHONE_NUMBER', '')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', 'example')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', 'example')
ONESIGNAL_APP_ID = os.getenv('ONESIGNAL_APP_ID', '07ed4c08-3698-4fdd-80c5-2de973b851ef')
ONESIGNAL_APIKEY = os.getenv('ONESIGNAL_APIKEY', 'MThiOWYzOWYtOThkMC00MGI1LWJiMzMtM2QwNDMwYmE1Mzlh')

ACCOUNT_LOGOUT_ON_GET = False

STRIPE_API_KEY = os.getenv('STRIPE_API_KEY', 'sk_test_AwTUfAFu61uxi8uGLm5FSEJE00idcE0OEk')

SEGMENT_WRITE_KEY = os.getenv('SEGMENT_WRITE_KEY', '6RqLquK0M8YzTVdhHJz3C5NSa0Tqli8v')

ACCOUNT_EMAIL_VERIFICATION = 'none'

FRONT_URL = os.getenv('FRONT_URL', 'front-dev-freelance.scenario-projects.com')
CONTACT_US_URL = 'https://{}/dashboard/help'.format(FRONT_URL)
WEBSITE_URL = 'https://{}'.format(FRONT_URL)

MP4_PIPELINE_ID = os.getenv('MP4_PIPELINE_ID', '1577369677921-qwavil')
MP4_TRANSCODER_PRESET_ID = os.getenv('MP4_TRANSCODER_PRESET_ID', '1351620000001-000010')


SOCIAL_AUTH_APPLE_KEY_ID = os.getenv('SOCIAL_AUTH_APPLE_KEY_ID', '76MWF8X6M3')
SOCIAL_AUTH_APPLE_TEAM_ID = os.getenv('SOCIAL_AUTH_APPLE_TEAM_ID', 'L6D4MNLA5U')
SOCIAL_AUTH_APPLE_CLIENT_ID = os.getenv('SOCIAL_AUTH_APPLE_CLIENT_ID', 'com.wurknet.mobile')
SOCIAL_AUTH_WEB_APPLE_CLIENT_ID = os.getenv('SOCIAL_AUTH_APPLE_CLIENT_ID', 'com.wurknet.mobile.service')
SOCIAL_AUTH_APPLE_PRIVATE_KEY = '''
-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0vQkK/b6cf5nwqZw
ACAswvR1Sgui7AKE1ymOGHHc1vugCgYIKoZIzj0DAQehRANCAAStW189CQYstrrt
wdH/sif3Kt4HcXwFgcJ69HnA/aqLEqusx8giLfXuKBuOM99FsBXlo3hCyb/YjK2M
5ua1DTH5
-----END PRIVATE KEY-----
'''

GOOGLE_BUNDLE_ID = os.getenv('GOOGLE_BUNDLE_ID', 'example.bundle')
GOOGLE_SERVICE_ACCOUNT_KEY_FILE = os.getenv('GOOGLE_SERVICE_ACCOUNT_KEY_FILE', 'example.bundle')
APPLE_BUNDLE_ID = os.getenv('APPLE_BUNDLE_ID', 'example.bundle')

# INSTAGRAM_API_CLIENT_ID = os.getenv('INSTAGRAM_API_CLIENT_ID', '1249340341943985')
# INSTAGRAM_API_CLIENT_SECRET = os.getenv('INSTAGRAM_API_CLIENT_SECRET', '1eb6a178285043e55c1bdd7d4e73e4a3')
# INSTAGRAM_REDIRECT_URL = os.getenv('INSTAGRAM_REDIRECT_URL', 'https://back-dev-freelance.scenario-projects.com/')

INSTAGRAM_API_CLIENT_ID = os.getenv('INSTAGRAM_API_CLIENT_ID', '1249340341943985')
INSTAGRAM_API_CLIENT_SECRET = os.getenv('INSTAGRAM_API_CLIENT_SECRET', '1eb6a178285043e55c1bdd7d4e73e4a3')
INSTAGRAM_REDIRECT_URL = os.getenv('INSTAGRAM_REDIRECT_URL', 'https://dev.1worknetwork.com/dashboard/account')


TWITTER_ACCESS_TOKEN = os.getenv('TWITTER_ACCESS_TOKEN', '756173937130766336-CiFVnyxmQFddis6mjW1SYrh3DFCzv5z')
TWITTER_ACCESS_TOKEN_SECRET = os.getenv('TWITTER_ACCESS_TOKEN_SECRET', 'DLCdTtph7eZ1UVd5O4JfbkyMQv67hOWwD591ZyrngiPTR')
TWITTER_CUSTOMER_API_KEY = os.getenv('TWITTER_ACCESS_TOKEN', 'llqApN9vKJz2Rn4moGa3CChUw')
TWITTER_CUSTOMER_API_SECRET_KEY = os.getenv('TWITTER_ACCESS_TOKEN', 'B2OYrFneHnIBvB03M8vLrfKj7ENEKgrJzT3rTDsG2R2KY3Hqzk')

LOCAL_CURRENCY = os.getenv('LOCAL_CURRENCY', 'inr')
LOCAL_COUNTRY = os.getenv('LOCAL_COUNTRY', 'IN')

# ------------ SENTRY ---------- #
SENTRY_DSN = os.getenv('SENTRY_DNS')

# Sentry Initializations.
sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment=os.getenv('ENVIRONMENT'),
    integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
    attach_stacktrace=True,
    send_default_pii=True
)

# ----------- FRESHCHAT ---------#
# TODO(Nishant): Add all this to CI repo.
FRESHCHAT_BASE_URL = "https://api.in.freshchat.com/v2"
FRESHCHAT_USER_CREATION_ALLOWED = False if os.getenv('FRESHCHAT_USER_CREATION_ALLOWED', True) == 'False' else True
FRESHCHAT_APP_ID = os.getenv('FRESHCHAT_APP_ID')
FRESHCHAT_MESSAGING_PHONE_NUMBER = os.getenv('FRESHCHAT_MESSAGING_PHONE_NUMBER')
FRESHCHAT_WHATSAPP_NAMESPACE = os.getenv('FRESHCHAT_WHATSAPP_NAMESPACE')
FRESHCHAT_ACCESS_TOKEN = os.getenv('FRESHCHAT_ACCESS_TOKEN')

# All environment variables.
ENVIRONMENT = os.getenv('ENVIRONMENT')
ENVIRONMENT_PREPROD = "preprod"
ENVIRONMENT_PROD = "prod"
ENVIRONMENT_STAGE = "stage"
ENVIRONMENT_DEV = "dev"

GOOGLE_API_ACCOUNT_TYPE = os.getenv('GOOGLE_API_ACCOUNT_TYPE', '')
GOOGLE_API_PROJECT_ID = os.getenv('GOOGLE_API_PROJECT_ID', '')
GOOGLE_API_PRIVATE_KEY_ID = os.getenv('GOOGLE_API_PRIVATE_KEY_ID', '')
GOOGLE_API_PRIVATE_KEY = os.getenv('GOOGLE_API_PRIVATE_KEY', '').replace('\\n', '\n')
GOOGLE_API_CLIENT_EMAIL = os.getenv('GOOGLE_API_CLIENT_EMAIL', '')
GOOGLE_API_CLIENT_ID = os.getenv('GOOGLE_API_CLIENT_ID', '')
GOOGLE_API_AUTH_URI = os.getenv('GOOGLE_API_AUTH_URI', '')
GOOGLE_API_TOKEN_URI = os.getenv('GOOGLE_API_TOKEN_URI', '')
GOOGLE_API_AUTH_PROVIDER_CERT_URL = os.getenv('GOOGLE_API_AUTH_PROVIDER_CERT_URL', '')
GOOGLE_API_CLIENT_CERT_URL = os.getenv('GOOGLE_API_CLIENT_CERT_URL', '')

# Google credentials to access API.
GOOGLE_API_CREDENTIALS = {
  "type": GOOGLE_API_ACCOUNT_TYPE,
  "project_id": GOOGLE_API_PROJECT_ID,
  "private_key_id": GOOGLE_API_PRIVATE_KEY_ID,
  "private_key": GOOGLE_API_PRIVATE_KEY,
  "client_email": GOOGLE_API_CLIENT_EMAIL,
  "client_id": GOOGLE_API_CLIENT_ID,
  "auth_uri": GOOGLE_API_AUTH_URI,
  "token_uri": GOOGLE_API_TOKEN_URI,
  "auth_provider_x509_cert_url": GOOGLE_API_AUTH_PROVIDER_CERT_URL,
  "client_x509_cert_url": GOOGLE_API_CLIENT_CERT_URL
}


SUPERPRO_BASE_URL = "https://roomsvc-dot-sprpro-282209.el.r.appspot.com"
SUPERPRO_ACCESS_TOKEN = os.getenv('SUPERPRO_ACCESS_TOKEN', '')

AGORA_APP_ID = os.getenv('AGORA_APP_ID', 'b935ed15c20644e59df9c946681e1dd5')
AGORA_APP_CERTIFICATE = os.getenv('AGORA_APP_CERTIFICATE', 'eaedc7539d8747b99b61ab55d17fe463')