TRANSACTION_TYPE_CRATER_TO_CREATOR_ENUM = 1
TRANSACTION_TYPE_CREATOR_TO_USER_ENUM = 2
TRANSACTION_TYPE_USER_TO_USER_ENUM = 3
TRANSACTION_TYPE_USER_TO_CREATOR_ENUM = 4

TRANSACTION_TYPE_CRATER_TO_CREATOR = "Crater to Creator"
TRANSACTION_TYPE_CREATOR_TO_USER = "Creator to User"
TRANSACTION_TYPE_USER_TO_USER = "User to User"
TRANSACTION_TYPE_USER_TO_CREATOR = "User to Creator"
