from django.contrib.auth import get_user_model

EMAILS = [
    "niranjanaiyer7@gmail.com",
    "rewari.vishal@gmail.com",
    "sumeet@skafinance.in",
    "jkirit@gmail.com",
    "kiran.paul.j@icloud.com",
    "antice@gmail.com",
    "minhancecoach@gmail.com",
    "msshirgaonkar@gmail.com",
    "shrihari@sagestreet.in",
    "rushabhtjain@gmail.com",
    "kunal.shah013@gmail.com",
    "ozapankaj@gmail.com",
    "ujwal.thombre@nexcel.co.in",
    "aloy920@gmail.com",
    "pujakotecha1@gmail.com",
    "dharmin.chanda@gmail.com",
    "design@wegroup.in",
    "abhishek@worknetwork.in",
    "acsrujan@gmail.com",
    "shriya@docvita.in",
    "shubham.kant@outlook.in",
    "darshandoshi666@gmail.com",
    "vijitpitliya@gmail.com",
    "nikhilpriya382@yahoo.com",
    "yash.kanoi@gmail.com",
    "singh.jaswanth1@gmail.com",
    "nikhil8k@gmail.com",
    "krishnabang3@gmail.com",
    "vikram.vma@gmail.com",
    "nehasikri14@gmail.com",
    "ellora@aliveinconnection.com",
    "hrshtvardhan@gmail.com",
    "siddharth.manchanda1@gmail.com",
    "jaideep.bachher@gmail.com",
    "medha@sarvasamya.com",
    "kritikasethi4@gmail.com",
    "anshul@easybizconsulting.com",
    "ashmitadutta.bink@gmail.com",
    "rjtnndn@gmail.com",
    "suneetjohn@triggerworldwide.com",
    "deeptitarakanath@gmail.com",
    "ratsam93@gmail.com",
    "sahil@irislivingspaces.com",
    "yashwanthyash046@gmail.com",
    "learnglobally2020@gmail.com",
    "komal.socionetic@gmail.com",
    "prakashnimbal@gmail.com",
    "mane.siddhesh31@gmail.com",
    "yash@worknetwork.in",
    "hrishikeshpatel@outlook.com",
    "vijay@vraheja.com",
    "nishant@worknetwork.in",
    "study.raaz@gmail.com",
    "have@jardens.in",
    "contact.sundeepteki@gmail.com",
    "mayank@rivi.co",
    "vishwas@codemire.com",
    "princekumar.rkt@gmail.com",
    "kenneth@sensio-ai.in",
    "hardhik.sheth@gmail.com",
    "prachi.sharma@vizinfy.com",
    "sjvipin@gmail.com",
    "syedyasser1995@gmail.com",
    "sujay.patole@nishdatasolutions.com",
    "nittenbz@gmail.com",
    "gangwalca@hotmail.com",
    "riteshrajs@gmail.com",
    "manishkumarsaraf@gmail.com",
    "aravindh27@gmail.com",
    "mawasthi@oorjagram.in",
    "dhanushariah@gmail.com",
    "saiqat@yahoo.com",
    "abhishek.doshi90@gmail.com",
    "lizannfdz@gmail.com",
    "9puneeta@iima.ac.in",
    "anand.kumar@transformation-advisory.com",
    "ankur8gupta@gmail.com",
    "dushyant@citispotter.com",
    "raginibajaj@yahoo.com",
    "tankha@tankhadesign.com",
    "ambujtyagi@hotmail.com",
    "playgroundarchitecture@gmail.com",
    "bharat@socialkyte.com",
    "vignesh@worknetwork.in",
    "anmol@docvita.in",
    "katralvikrant@yahoo.com",
    "modianish11@gmail.com",
    "sanskarraj25@gmail.com",
    "towardsmanil@gmail.com",
    "himanshu.blue0508@gmail.com",
    "tarun@cokarma.in",
    "abhikuiitk@gmail.com",
    "sameer@faebikes.com",
    "karankhattar01@gmail.com",
    "shubhangibansal70@gmail.com",
    "rv@matelabs.in",
    "anand.dx001@gmail.com",
    "himalayanmirrors@gmail.com",
    "salesjax79@gmail.com",
    "bpbala2005@gmail.com",
    "vineet@cohire.co.in",
    "sursma@gmail.com",
    "vijay@superpro.ai",
    "founder@blockdeliver.in",
    "akash@millennialstreets.com",
    "skyleoglobal@gmail.com",
    "dm@kepsla.com",
    "amritansh@neurodynamic.in",
    "mayank@vividworx.in",
    "angshuman@trustinsolutions.com",
    "subham.charan@varistor.in",
    "amritarya@indibuff.com",
    "arcot@cognateglobal.com",
    "suman@myzila.com",
    "ishu.darshan@check-in.in",
    "tanishq@skyber.cloud",
    "akshay@mergeintern.com",
    "manish@ovonts.com",
    "ps@drivify.in",
    "shivam@apli.ai",
    "shrenikjain1996@gmail.com",
    "rajpal.fogawat@gmail.com",
    "gaurav@avataar.me",
    "hana@inkrepublique.com",
    "arjunarora108@gmail.com",
    "bharath@livethesport.life",
    "naresh@untangle.ai",
    "akshay@nasch.io",
    "aman.telkar@gmail.com",
    "siva@altf9.tech",
    "zohaaibkhan007@gmail.com",
    "gt@superpro.ai",
    "hemant@nextphase.co.in",
    "asinha@xpcover.com",
    "kittu_mbk@hotmail.com",
    "tarun.gupta@freshconnect.in",
    "vivan@worknetwork.in",
    "bhawna.bhatnagar27@gmail.com",
    "nishchal@firstma.in",
    "shreyasnaik2601@gmail.com",
    "piyusharora2k6@gmail.com",
    "abishek.surendran@gmail.com",
    "anirudh@021.capital",
    "anup@oriosvp.com",
    "svinod3@gmail.com",
    "debasis@mainstage-incubator.com",
    "abhinavmishra.imtn@gmail.com",
    "prafful@indianangelnetwork.com",
    "prakashpartha@dream11.com",
    "vidhi.13jain@gmail.com",
    "adalvi2796@gmail.com",
    "raovarun22@gmail.com"
]


def run(dry_run=True):

    for email in EMAILS:

        print("Start", "-"*30)
        print("Email: {}".format(email))
        try:
            user = get_user_model().objects.get(email=email)
        except get_user_model().DoesNotExist:
            print("***** User doesn't exist: {}".format(email))
            continue

        if not user.has_profile:
            print("***** User doesn't have profile: {}".format(email))

        profile = user.profile
        print("User Score: {}".format(user.score))

        if not dry_run:
            profile.allow_meeting_request = True
            profile.save()
            print("Allowed for meeting requests")

        print("End", "-" * 30)
