from resources.meetings import choices
from resources.meetings import models
from users import models as user_models

user_interest_map = {
    "siddharthrao.rao@gmail.com": ["Business Advisors", "Designers & Marketers", "Founders"],
    "gr8radhika@hotmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Business Advisors",
                               "Financial Experts", "Founders", "Influencers"],
    "suryadeep.boda@gmail.com": ["Business Advisors", "Founders", "Influencers", "Business Advisors", "Founders",
                                 "Influencers"],
    "studioneelabh@gmail.com": ["Founders", "Founders"],
    "uditvar@gmail.com": ["Executives", "Founders", "Influencers", "Investors", "Executives", "Founders", "Influencers",
                          "Investors"],
    "rashisaraf@gmail.com": ["Founders", "Executives", "Founders", "Investors"],
    "dhanushariah@gmail.com": ["Business Advisors", "Designers & Marketers", "Founders", "Investors",
                               "Business Advisors", "Executives", "Financial Experts", "Founders", "Investors",
                               "Lawyers"],
    "vmgtradelynks@gmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors",
                                "Lawyers"],
    "shourichikkerur@gmail.com": ["Founders"],
    "marketing@worknetwork.in": ["Investors", "Designers & Marketers"],
    "navyarudresh15@gmail.com": ["Business Advisors", "Influencers", "Investors", "Business Advisors", "Influencers",
                                 "Investors"],
    "amulya@pepperinteractive.in": ["Founders", "Influencers", "Investors", "Financial Experts", "Founders", "Lawyers"],
    "mukesh@rupyaapaisa.com": ["Business Advisors"],
    "kirtijain3107@gmail.c": ["Founders"],
    "radhika.gupte7@gmail.com": ["Investors"],
    "dhanshek9@gmail.com": ["Business Advisors"],
    "printshoppe77@gmail.com": ["Executives"],
    "pradeepharishkumar@gmail.com": ["Business Advisors"],
    "tarunasabikhi@gmail.com": ["Investors"],
    "nakkaganesh93@gmail.com": ["Founders"],
    "cs.venugopalrao@gmail.com": ["Business Advisors"],
    "mr.prashantraichura@gmail.com": ["Financial Experts"],
    "alekhyagosai@gmail.com": ["Investors"],
    "s.naman10@gmail.com": ["Financial Experts"],
    "sandeshgamre@yahoo.com": ["Business Advisors"],
    "mate.dinesh852@gmail.com": ["Business Advisors"],
    "sushgam@gmail.com": ["Business Advisors"],
    "vidhurathi001@gmail.com": ["Business Advisors", "Influencers"],
    "dheeraj17118@gmail.com": ["Business Advisors", "Founders"],
    "anupnair1994@gmail.com": ["Business Advisors", "Investors"],
    "sudheer.ece2008@gmail.com": ["Financial Experts"],
    "indurekha.artist@gmail.com": ["Influencers"],
    "Dineetkohli@gmail.com": ["Business Advisors"],
    "prashant@transganization.com": ["Founders"],
    "aishusinghi98@gmail.com": ["Influencers"],
    "microplanetindia@gmail.com": ["Investors"],
    "akanksha.pol.1@gmail.com": ["Influencers", "Investors"],
    "kumaran.rt7@gmail.com": ["Business Advisors"],
    "paashu94@gmail.com": ["Business Advisors"],
    "chethanr461@gmail.com": ["Business Advisors"],
    "ramu.varun@gmail.com": ["Investors"],
    "davechinmay23@gmail.com": ["Business Advisors", "Founders", "Investors"],
    "mk4597682@gmail.com": ["Investors"],
    "n.yuvstar1234@gmail.com": ["Investors"],
    "aditya-dalvi@outlook.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Investors",
                                 "Business Advisors", "Executives", "Financial Experts", "Founders", "Investors"],
    "vivan@worknetwork.in": ["Lawyers", "Business Advisors"],
    "hamarasalesandmarketing@gmail.com": ["Business Advisors", "Founders"],
    "nareshkumarm352@gmail.com": ["Business Advisors"],
    "udayabhaskr4@gmail.com": ["Investors"],
    "sahananandhi@gmail.com": ["Business Advisors"],
    "casrpandya@gmail.com": ["Financial Experts"],
    "ajay91@live.in": ["Investors"],
    "shraddhatripathi185@gmail.com": ["Founders"],
    "nikhilwork005@gmail.com": ["Founders", "Investors"],
    "nakulpatilnp@gmail.com": ["Business Advisors"],
    "buxmedia03@gmail.com": ["Investors"],
    "jjnikhil@gmail.com": ["Investors"],
    "dhruvrjpl@gmail.com": ["Business Advisors", "Influencers"],
    "imranmohammed21@gmail.com": ["Founders"],
    "dhaval89in@gmail.com": ["Financial Experts"],
    "info@thewebstory.com": ["Founders"],
    "sbisht670@gmail.com": ["Influencers"],
    "venkks@upspring.it": ["Investors"],
    "sarabjeet@fundingventures.in": ["Investors"],
    "satishsvk@yahoo.com": ["Business Advisors"],
    "ankitverma2676@gmail.com": ["Investors"],
    "ameershetty.shirish@gmail.com": ["Executives"],
    "shreyasnaik2601@gmail.com": ["Investors"],
    "sgreyasnaik2601@gmail.com": ["Founders"],
    "abishektated1020@gmail.com": ["Investors"],
    "manzar298@gmail.com": ["Business Advisors"],
    "shubhamahlawat12@gmail.com": ["Investors"],
    "sevanthi2010@gmail.com": ["Investors"],
    "sauravchatterjii@gmail.com": ["Investors"],
    "hanit_nijhawan@tcsinternational.in": ["Business Advisors"],
    "nigammihir8@gmail.com": ["Business Advisors"],
    "khiral143@gmail.com": ["Executives"],
    "vijayameghana48@gmail.com": ["Investors", "Business Advisors", "Engineers", "Executives", "Influencers",
                                  "Investors"],
    "csnidhisinghania@gmail.com": ["Founders"],
    "arbi2012.ab@gmail.com": ["Influencers"],
    "veehan077@gmail.com": ["Founders"],
    "mansirao.hpt@gmail.com": ["Business Advisors", "Influencers"],
    "rokhsifatima@gmail.com": ["Influencers"],
    "deepika.medpal@gmail.com": ["Business Advisors", "Lawyers"],
    "sunilgowda.k.m40@gmail.com": ["Investors"],
    "prashant.tetali@gmail.com": ["Executives"],
    "vijeshgiri@gmail.com": ["Business Advisors"],
    "allinceindustries@gmail.com": ["Executives"],
    "aniruddhap@whitepapercrew.com": ["Founders"],
    "rishabhkunwar@gmail.com": ["Founders"],
    "nishantvermaweb@gmail.com": ["Business Advisors", "Founders", "Business Advisors", "Founders"],
    "sameer@faebikes.com": ["Founders"],
    "kiran.paul.j@icloud.com": ["Executives", "Founders", "Investors", "Executives", "Founders"],
    "abhishek@worknetwork.in": ["Influencers"],
    "anup@oriosvp.com": ["Investors"],
    "piyusharora2k6@gmail.com": ["Founders", "Investors"],
    "pikubadia@gmail.com": ["Investors"],
    "bginfotech2003@gmail.com": ["Founders"],
    "nishant.gambhir22@gmail.com": ["Business Advisors"],
    "support@movifi.co": ["Investors"],
    "niteshkan@gmail.com": ["Business Advisors"],
    "kinnshuk@gmail.com": ["Business Advisors", "Financial Experts", "Influencers", "Investors", "Business Advisors",
                           "Financial Experts", "Influencers", "Investors"],
    "hk12@iitbbs.ac.in": ["Founders"],
    "sanskarraj25@gmail.com": ["Founders", "Business Advisors", "Executives", "Financial Experts"],
    "sreenivas.dega@gmail.com": ["Engineers", "Founders"],
    "ajit.p.pol@gmail.com": ["Founders", "Investors", "Founders", "Investors"],
    "physioshikha23@gmail.com": ["Business Advisors"],
    "ankithgl007@gmail.com": ["Founders"],
    "vaishnav.vivek234@gmail.com": ["Business Advisors"],
    "marketwithmaddy@gmail.com": ["Founders"],
    "waseem.klazina@gmail.com": ["Financial Experts"],
    "ayushdokania995@gmail.com": ["Investors"],
    "yogy21.1992@gmail.com": ["Founders"],
    "rakshitsubbegowda@gmail.com": ["Founders"],
    "tannuhere7@gmail.com": ["Business Advisors"],
    "yogeshratna.javvadi@gmail.com": ["Business Advisors"],
    "stormyclicks@gmail.com": ["Founders"],
    "karmeshghosh@gmail.com": ["Business Advisors", "Executives", "Founders", "Investors"],
    "shristisethia8@gmail.com": ["Business Advisors"],
    "shreshthkanoria@yahoo.in": ["Business Advisors"],
    "monishshah81@gmail.com": ["Business Advisors"],
    "akshaybhegde11@gmail.com": ["Founders"],
    "alung.nikhil@gmail.com": ["Investors"],
    "dshobhan2010@gmail.com": ["Business Advisors"],
    "Chiraag@neonbroadband.com": ["Investors"],
    "fgosar@gmail.com": ["Influencers"],
    "radeongraphics88@gmail.com": ["Business Advisors"],
    "Meherangiskaranjia@gmail.com": ["Founders"],
    "virgo.prateek@gmail.com": ["Business Advisors"],
    "digitalsubodh.in@gmail.com": ["Founders"],
    "kkr.963275@gmail.com": ["Influencers"],
    "saumyadeep.taxitopmedia@gmail.com": ["Business Advisors", "Executives", "Business Advisors", "Executives"],
    "shivani.divecha@gmail.com": ["Influencers"],
    "shekarc350@gmail.com": ["Business Advisors"],
    "sumit_cp@hotmail.com": ["Investors"],
    "vijayyashwanth@gmail.com": ["Founders"],
    "bharti.saurav@gmail.com": ["Investors"],
    "abhishekkanoor@gmail.com": ["Investors"],
    "ryback4eva@gmail.com": ["Business Advisors"],
    "shhauryamehta22@gmail.com": ["Investors"],
    "Bhardwajaakash15@gmail.com": ["Business Advisors"],
    "syedshoebsk903@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors",
                                 "Business Advisors", "Executives", "Founders", "Influencers"],
    "mht.shrm15@gmail.com": ["Executives"],
    "mehtaameesha04@gmail.com": ["Founders"],
    "sandeep.bondre@gmail.com": ["Influencers", "Influencers"],
    "vignesh@worknetwork.in": ["Business Advisors", "Designers & Marketers"],
    "rabi@alfasilicon.com": ["Founders", "Business Advisors", "Engineers", "Financial Experts", "Founders"],
    "study.raaz@gmail.com": ["Founders", "Investors", "Founders", "Investors"],
    "karthik@dextercapital.in": ["Founders"],
    "priyeshjain2601@gmail.com": ["Executives", "Financial Experts", "Lawyers"],
    "anishkumar.trainer@gmail.com": ["Investors", "Investors"],
    "sigmaengineers2019@gmail.com": ["Business Advisors", "Financial Experts", "Investors", "Business Advisors",
                                     "Financial Experts", "Investors"],
    "athulpr@gmail.com": ["Financial Experts"],
    "abhishek.doshi90@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                   "Investors", "Lawyers", "Business Advisors", "Executives", "Financial Experts",
                                   "Founders", "Influencers", "Investors", "Lawyers"],
    "govind.mapel@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                               "Investors", "Lawyers", "Business Advisors", "Executives", "Financial Experts",
                               "Founders", "Influencers", "Investors", "Lawyers"],
    "jatinlangyan@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Influencers",
                               "Business Advisors", "Executives", "Financial Experts", "Influencers"],
    "rahul@thunderpod.com": ["Founders", "Investors", "Founders"],
    "meherpritesh97@gmail.com": ["Business Advisors", "Influencers", "Investors", "Business Advisors", "Influencers",
                                 "Investors"],
    "naveensangeeth@yahoo.com": ["Investors", "Investors"],
    "paritosh.gupta@agilytics.in": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                    "Investors"],
    "devdkumar22@gmail.com": ["Influencers", "Influencers"],
    "shyamvenu@gmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors"],
    "nsnikhil666@gmail.com": ["Business Advisors", "Financial Experts", "Influencers", "Investors", "Lawyers",
                              "Business Advisors", "Financial Experts", "Influencers", "Investors", "Lawyers"],
    "topfashiond@gmail.com": ["Business Advisors", "Business Advisors"],
    "heepcares@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors"],
    "sakethkumar.97@gmail.com": ["Engineers"],
    "abdullah.aftab920@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors"],
    "tejaseshu@mcaspirant.com": ["Executives", "Financial Experts", "Influencers", "Investors"],
    "kumarbdua@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors"],
    "manali.agrawal@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Investors",
                                 "Lawyers"],
    "kohlirajanpal77@gmail.com": ["Business Advisors", "Executives", "Influencers"],
    "roshan@bxstudio.in": ["Influencers"],
    "siddharth.b.krish@gmail.com": ["Founders", "Investors"],
    "smarthyvasdev@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers"],
    "suzaina@mavericking.com": ["Executives", "Founders", "Executives", "Founders", "Investors"],
    "swetamaskara1980@gmail.com": ["Business Advisors", "Investors", "Business Advisors", "Investors"],
    "aditya@chiratae.com": ["Founders", "Investors"],
    "nmedappa@gmail.com": ["Designers & Marketers", "Executives"],
    "solutionsatpar17@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors", "Business Advisors",
                                   "Founders", "Influencers", "Investors"],
    "purplejukebox@outlook.com": ["Influencers"],
    "yashraj@kredits.in": ["Founders"],
    "rinkisingh777@gmail.com": ["Executives", "Financial Experts", "Founders", "Influencers", "Investors", "Executives",
                                "Financial Experts", "Founders", "Influencers", "Investors"],
    "anubhab.sarkar@triumvirlaw.com": ["Business Advisors", "Executives", "Financial Experts", "Investors", "Lawyers"],
    "sandip@capalaventures.com": ["Founders"],
    "rv@matelabs.in": ["Engineers", "Founders", "Investors"],
    "manishkumarsaraf@gmail.com": ["Founders", "Influencers", "Business Advisors", "Designers & Marketers", "Founders",
                                   "Influencers"],
    "samarth@primevp.in": ["Founders", "Investors"],
    "prerita@live.com": ["Influencers"],
    "minhancecoach@gmail.com": ["Executives", "Founders", "Executives"],
    "debjit@itsindia.in": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                           "Investors", "Business Advisors", "Executives", "Financial Experts", "Founders",
                           "Influencers", "Investors"],
    "k.naresh95@skrgm.com": ["Financial Experts"],
    "naveen@streetstylestalk.com": ["Designers & Marketers"],
    "surya.kiran0805@gmail.com": ["Designers & Marketers"],
    "santhoshkrs0413@gmail.com": ["Designers & Marketers"],
    "sachinraj.jain@outlook.com": ["Business Advisors"],
    "tehzeebg@gmail.com": ["Designers & Marketers"],
    "gaurvi.sharma@mastertrust.co": ["Influencers"],
    "arulovesworking@gmail.com": ["Financial Experts"],
    "theemesindia@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors"],
    "dee22894@gmail.com": ["Business Advisors"],
    "amrek1982@gmail.com": ["Influencers"],
    "singh.karanvirsingh@gmail.com": ["Designers & Marketers"],
    "msshirgaonkar@gmail.com": ["Founders"],
    "ingawale.ajinkya1@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors"],
    "himani@shrexlearning.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                 "Investors", "Lawyers"],
    "nishantkparashar@gmail.com": ["Engineers"],
    "karor29@gmail.com": ["Influencers", "Influencers"],
    "dharmin.chanda@gmail.com": ["Executives", "Founders", "Influencers", "Executives", "Founders", "Influencers"],
    "vishnu.acharya@razorpay.com": ["Financial Experts", "Founders"],
    "rajesh@venturecatalysts.in": ["Founders"],
    "aditya@wisemonk.co": ["Founders", "Investors", "Business Advisors", "Founders", "Investors"],
    "hello@firstma.in": ["Founders", "Investors"],
    "yeshwanth.sonnathi@alumni.ashoka.edu.in": ["Business Advisors", "Executives", "Founders", "Executives",
                                                "Founders"],
    "dizaarts@yahoo.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Business Advisors",
                           "Executives", "Financial Experts", "Founders", "Influencers", "Investors"],
    "prateek460f@gmail.com": ["Influencers", "Influencers"],
    "ramesh_choudhary1987@yahoo.com": ["Business Advisors", "Financial Experts", "Business Advisors",
                                       "Financial Experts"],
    "wadkarsanku@gmail.com": ["Financial Experts", "Founders", "Influencers", "Investors", "Financial Experts",
                              "Founders", "Influencers", "Investors"],
    "pratap.gunjan@hotmail.com": ["Business Advisors", "Executives", "Financial Experts", "Investors",
                                  "Business Advisors", "Executives", "Financial Experts", "Investors"],
    "venkatesh.l8081989@outlook.com": ["Business Advisors", "Business Advisors"],
    "caprake1185@gmail.com": ["Business Advisors", "Founders", "Influencers", "Investors", "Business Advisors",
                              "Founders", "Influencers", "Investors"],
    "mohammadmustafa2k19@gmail.com": ["Business Advisors", "Executives", "Business Advisors", "Executives"],
    "vigneshrajm@hotmail.com": ["Influencers"],
    "himalayanmirrors@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Business Advisors",
                                   "Executives", "Founders", "Influencers"],
    "bhupathi955@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Business Advisors",
                              "Executives", "Founders", "Influencers"],
    "senthil@zinnov.com": ["Designers & Marketers", "Engineers", "Founders"],
    "netabhijitdas@gmail.com": ["Business Advisors", "Business Advisors"],
    "shahpranu27@yahoo.com": ["Influencers", "Influencers"],
    "leemarose.27.2@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors",
                                 "Business Advisors", "Executives", "Founders", "Influencers", "Investors"],
    "abishek.surendran@gmail.com": ["Founders"],
    "manojvyas.ee@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                               "Investors", "Lawyers", "Business Advisors", "Executives", "Financial Experts",
                               "Founders", "Influencers", "Investors", "Lawyers"],
    "nocodeparas@gmail.com": ["Founders", "Investors"],
    "yash.kanoi@gmail.com": ["Founders"],
    "sriram.anaga@gmail.com": ["Investors", "Engineers"],
    "bala@hellohotel.in": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors",
                           "Business Advisors", "Executives", "Founders", "Influencers", "Investors"],
    "241kaushik@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Lawyers",
                             "Investors"],
    "anand.dx001@gmail.com": ["Business Advisors", "Engineers", "Founders", "Investors", "Designers & Marketers",
                              "Founders", "Influencers", "Lawyers"],
    "vatsa@standout.digital": ["Founders"],
    "shobbhitnaagar@gmail.com": ["Business Advisors", "Designers & Marketers", "Founders", "Influencers", "Investors",
                                 "Designers & Marketers", "Founders", "Influencers", "Investors"],
    "ganesh.mallya@gmail.com": ["Founders", "Investors"],
    "yashrajbafna@gmail.com": ["Founders", "Investors"],
    "dhiman96sanjana@gmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors"],
    "jitendranag20@gmail.com": ["Influencers", "Influencers"],
    "stuti@iaol.co.in": ["Designers & Marketers", "Founders"],
    "aishwaryaagrawal06@gmail.com": ["Business Advisors", "Designers & Marketers", "Executives", "Founders",
                                     "Influencers"],
    "w.g.k.singh05@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                "Investors"],
    "yadavsudha8512@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                 "Investors", "Lawyers", "Business Advisors", "Executives", "Financial Experts",
                                 "Founders", "Influencers", "Investors", "Lawyers"],
    "amitpal.rawat@gmail.com": ["Executives", "Founders", "Executives", "Founders"],
    "amaheshwari1976@gmail.com": ["Financial Experts", "Founders", "Investors"],
    "sanyamjain2408@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                                 "Investors", "Lawyers"],
    "saurabhpedia@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors"],
    "samkith.baba@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors",
                               "Business Advisors", "Executives", "Founders", "Influencers", "Investors"],
    "flyrub@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Influencers", "Investors",
                         "Business Advisors", "Executives", "Financial Experts", "Influencers", "Investors"],
    "nikhilpriya382@yahoo.com": ["Financial Experts", "Lawyers", "Investors"],
    "priyanka96@gmail.com": ["Influencers"],
    "krithika.b95@gmail.com": ["Investors", "Investors"],
    "sanjeevkabir@gmail.com": ["Business Advisors", "Founders", "Business Advisors", "Founders"],
    "biswajit.nayak@helpuinvestment.co.in": ["Influencers", "Influencers"],
    "rsharma26@gmail.com": ["Financial Experts", "Investors"],
    "nobinkurian@yahoo.com": ["Business Advisors", "Influencers", "Business Advisors", "Influencers"],
    "rohannayyar5@gmail.com": ["Designers & Marketers", "Influencers"],
    "niteshghatal@gmail.com": ["Influencers"],
    "samarthfrancis1@gmail.com": ["Business Advisors", "Founders", "Investors"],
    "siddhantraniwala@gmail.com": ["Founders", "Founders"],
    "Priyanka1997sharma@gmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors",
                                     "Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors"],
    "swamy50@gmail.com": ["Financial Experts", "Investors", "Financial Experts", "Investors"],
    "cp.matar@gmail.com": ["Designers & Marketers", "Founders", "Influencers", "Investors"],
    "arshbiji@gmail.com": ["Business Advisors", "Executives", "Financial Experts", "Founders", "Influencers",
                           "Investors", "Lawyers", "Business Advisors", "Executives", "Financial Experts", "Founders",
                           "Influencers", "Investors", "Lawyers"],
    "richardslouis@doifoo.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Investors"],
    "tushar@dexterangels.com": ["Founders"],
    "balajikamineni@gmail.com": ["Founders", "Investors", "Founders", "Investors"],
    "borntoleadpeople@gmail.com": ["Influencers", "Influencers"],
    "chowdhuryamitava122@gmail.com": ["Influencers", "Investors", "Influencers", "Investors"],
    "kasinatahans1945@gmail.com": ["Investors", "Investors"],
    "Dear.pratik@gmail.com": ["Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors",
                              "Business Advisors", "Financial Experts", "Founders", "Influencers", "Investors"],
    "aglobalvyas21@gmail.com": ["Founders", "Investors", "Founders", "Investors"],
    "subhankar.chatterji@outlook.com": ["Executives", "Founders", "Influencers", "Investors", "Executives", "Founders",
                                        "Influencers", "Investors"],
    "bafnasanjay2000@yahoo.com": ["Business Advisors", "Designers & Marketers", "Founders", "Influencers", "Investors"],
    "kartikghali@gmail.com": ["Founders", "Influencers", "Investors", "Founders", "Influencers", "Investors"],
    "muktabahrani@gmail.com": ["Business Advisors", "Executives", "Founders", "Influencers", "Business Advisors",
                               "Executives", "Founders", "Influencers"],
    "saiqat@yahoo.com": ["Executives", "Founders", "Influencers", "Executives", "Founders", "Influencers"]
}


def run(dry_run=True):
    print("Starting population of interests")
    for user in user_models.User.objects.all():
        print("-" * 80)
        print(user.email)
        latest_meeting_preference = user.meeting_preferences.last()
        if not latest_meeting_preference:
            print("No meeting preference")
            print("-" * 80)
            continue

        all_interests = user_interest_map.get(user.email, [])
        preference_objectives = user.meeting_preferences.last().objective if user.meeting_preferences.last() else ''
        print("All selected interest for user: {}".format(all_interests))
        print("All selected objective for user: {}".format(preference_objectives))

        if not dry_run:
            print("Adding interests for user {}".format(user.email))

            interests = models.Interest.objects.filter(name__in=all_interests)
            for interest in interests:
                latest_meeting_preference.interests.add(interest)

            print("Getting objective for user.")
            # Get the objective name from the old objective field.
            old_objective_name = None
            for key, name in choices.OBJECTIVE_CHOICES:
                if key == preference_objectives:
                    old_objective_name = name

            objective_name = old_objective_name if old_objective_name else "Meet Interesting People"


            new_objective = models.Objective.objects.filter(
                name=objective_name
            ).last()

            if not new_objective:
                print("No objective for with the given name: {}".format(objective_name))
                continue

            latest_meeting_preference.objectives = new_objective
            latest_meeting_preference.save()

        print("-" * 80)
