# Generated by Django 3.0.2 on 2020-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'create_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
    ]
