# Generated by Django 2.2.7 on 2019-11-29 12:56
from django.contrib.auth.hashers import make_password
from django.db import migrations


def createsuperuser(apps, schema_editor):
    users = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    users.using(db_alias).get_or_create(
        email='admin@admin.com',
        username='Admin',
        is_superuser=True,
        is_active=True,
        is_staff=True,
        password=make_password('123qaz123!A'),
    )


def create_groups(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    exist_group_names = group.objects.values_list('name', flat=True)
    group_names = ['User', 'Investor']
    group.objects.bulk_create([group(name=name) for name in group_names if name not in exist_group_names])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createsuperuser, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_groups, reverse_code=migrations.RunPython.noop),
    ]
