# Generated by Django 2.2.7 on 2019-11-29 12:56
from django.db import migrations


def create_groups(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    exist_group_names = group.objects.values_list('name', flat=True)
    group_names = ['User', 'Investor', 'Admin', 'Support']
    group.objects.bulk_create([group(name=name) for name in group_names if name not in exist_group_names])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=migrations.RunPython.noop),
    ]
