# Generated by Django 3.0.2 on 2020-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_start',
            field=models.PositiveIntegerField(null=True, verbose_name='Price start'),
        ),
    ]
