# Generated by Django 3.0.2 on 2020-02-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_price_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.ImageField(null=True, upload_to='user/pan_card/%Y/%m/%d', verbose_name='Pan card'),
        ),
    ]
