# Generated by Django 3.0 on 2019-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Super User', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
