# Generated by Django 3.0.2 on 2020-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter'),
        ),
    ]
