# Generated by Django 3.0 on 2019-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason',
            field=models.CharField(choices=[('18_year_old', 'I am at least 18 year old.'), ('join', 'I want to join the community to collaborate or share.'), ('understand', 'I understand the membership appication process.')], max_length=100, null=True, verbose_name='Reason'),
        ),
    ]
