# Generated by Django 3.0.2 on 2020-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Instagram username'),
        ),
    ]
