# Generated by Django 3.0.3 on 2020-03-02 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_instagram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referer'),
        ),
    ]
