# Generated by Django 3.0 on 2019-12-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('locations', '0003_city_is_work'),
        ('users', '0006_user_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag line')),
                ('photo', models.ImageField(null=True, upload_to='profile/photo/%Y/%m/%d', verbose_name='Photo')),
                ('cover', models.FileField(null=True, upload_to='profile/cover/%Y/%m/%d', verbose_name='Cover')),
                ('introduction', models.CharField(blank=True, max_length=800, verbose_name='Introduction')),
                ('focus', models.CharField(blank=True, max_length=800, verbose_name='Focus')),
                ('additional_information', models.CharField(max_length=800, null=True, verbose_name='Additional Information')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('tags', models.ManyToManyField(related_name='profiles', to='tags.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('work_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City', verbose_name='Work city')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
