# Generated by Django 3.0.3 on 2020-04-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200302_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Instagram Id'),
        ),
    ]
