# Generated by Django 3.0 on 2019-12-13 09:53

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191211_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.FileField(null=True, upload_to='profile/cover/%Y/%m/%d', validators=[utils.validators.SizeValidator(size=512)], verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile/photo/%Y/%m/%d', validators=[utils.validators.SizeValidator(size=30)], verbose_name='Photo'),
        ),
    ]
