# Generated by Django 3.0.3 on 2020-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_secret_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Secret key'),
        ),
    ]
