# Generated by Django 3.0 on 2019-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_information',
            field=models.CharField(blank=True, default='', max_length=800, verbose_name='Additional Information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tag line'),
            preserve_default=False,
        ),
    ]
