# Generated by Django 3.0.3 on 2020-04-21 12:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_auth_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
