# Generated by Django 3.0.3 on 2020-05-21 07:13

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_new_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverfile',
            name='file',
            field=models.FileField(null=True, upload_to='profile/cover/%Y/%m/%d/', validators=[utils.validators.SizeValidator(size=512)], verbose_name='Cover'),
        ),
    ]
