# Generated by Django 3.0 on 2019-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191216_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=True, verbose_name='Public Profile'),
        ),
    ]
