# Generated by Django 3.0 on 2019-12-16 14:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_validated',
            field=models.BooleanField(default=False, verbose_name='Phone Number Validated'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Sms code'),
        ),
    ]
