# Generated by Django 3.0.3 on 2020-08-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_coverfile_blank_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('os', models.CharField(blank=True, max_length=32, null=True)),
                ('os_version', models.CharField(blank=True, max_length=32, null=True)),
                ('device_name', models.CharField(blank=True, max_length=256, null=True)),
                ('device_model', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-last_used',),
            },
        ),
    ]
