# Generated by Django 3.0.3 on 2020-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_coverfile_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=800, verbose_name='Linked In'),
        ),
    ]
