# Generated by Django 3.0 on 2019-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191216_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number_validated',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Number Verified'),
        ),
    ]
