# Generated by Django 3.0.3 on 2020-08-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_interests'),
        ('users', '0013_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.WorkCityProxy', verbose_name='Work city'),
        ),
    ]
