# Generated by Django 3.0 on 2019-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191216_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='User Approval.', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_service_approved',
            field=models.BooleanField(default=False, help_text='User Service Approval.', verbose_name='Service Approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Admin access for support.', verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Banned/Unbanned User.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Admin permissions, can be restricted by superadmin.', verbose_name='Admin'),
        ),
    ]
