# Generated by Django 3.0.3 on 2020-08-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200807_1629'),
        ('users', '0013_userdeviceinfo'),
    ]

    operations = [
    ]
