# Generated by Django 3.0 on 2019-12-17 13:00

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models

import users.managers


def createsuperuser(apps, schema_editor):
    users = apps.get_model('users', 'Admin')
    db_alias = schema_editor.connection.alias
    users.objects.using(db_alias).get_or_create(
        email='admin@admin.com',
        username='Admin',
        is_superuser=True,
        is_active=True,
        is_staff=True,
        name='Super User',
        password=make_password('123qaz123!A'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191217_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_support',
        ),
        migrations.RunPython(createsuperuser, reverse_code=migrations.RunPython.noop),
    ]
