# Generated by Django 3.0 on 2019-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191217_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reason',
            field=models.CharField(max_length=400, null=True, verbose_name='Reason'),
        ),
    ]
