# Generated by Django 3.0.3 on 2020-08-10 18:24

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20200807_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Photo Url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/photo/%Y/%m/%d', validators=[utils.validators.SizeValidator(size=30)], verbose_name='Photo'),
        ),
    ]
