# Generated by Django 3.0.3 on 2020-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_objective'),
        ('users', '0015_merge_20200807_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='objectives',
            field=models.ManyToManyField(to='tags.Objective', verbose_name='Objectives'),
        ),
    ]
