# Generated by Django 3.0.3 on 2020-08-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_photo_url'),
        ('users', '0016_user_objectives'),
    ]

    operations = [
    ]
