# Generated by Django 3.0.3 on 2020-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_interests'),
        ('users', '0016_add_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='tags.Interests', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_introduction',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Public Introduction'),
        ),
    ]
