# Generated by Django 3.0 on 2019-12-19 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191218_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referer'),
        ),
    ]
