# Generated by Django 3.0.3 on 2020-08-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20200812_1704'),
        ('users', '0017_auto_20200813_1812'),
    ]

    operations = [
    ]
