# Generated by Django 3.0 on 2019-12-21 11:21

from django.db import migrations, models
import django.db.models.deletion


def delete_cities(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('users', 'Profile')
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).update(city=None)
    Profile.objects.using(db_alias).update(work_city=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20191221_0915'),
        ('users', '0017_user_referer'),
    ]

    operations = [
        migrations.RunPython(delete_cities, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='work_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.WorkCityProxy', verbose_name='Work city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tags.CityProxy', verbose_name='City'),
        ),
    ]
