# Generated by Django 3.0.3 on 2020-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20200817_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_information',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Focus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Instagram Id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Linked In'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag line'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
    ]
