# Generated by Django 3.0 on 2019-12-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191221_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_thumbnail',
            field=models.URLField(null=True, verbose_name='Cover thumbnail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_transcoder',
            field=models.URLField(null=True, verbose_name='Cover transcoder'),
        ),
    ]
