# Generated by Django 3.0.3 on 2020-08-20 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200819_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='user/pan_card/%Y/%m/%d', verbose_name='Pan card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reason',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Sms code'),
        ),
    ]
