# Generated by Django 3.0 on 2019-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191225_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_old_cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='transcoder_job_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transcoder job id'),
        ),
        migrations.AddField(
            model_name='profile',
            name='transcoder_job_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='transcoder_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
