# Generated by Django 3.0 on 2019-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191227_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Cover thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_transcoder',
            field=models.URLField(blank=True, null=True, verbose_name='Cover transcoder'),
        ),
    ]
