# Generated by Django 3.0.3 on 2020-08-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200820_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Source'),
        ),
    ]
