# Generated by Django 3.0 on 2020-01-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191227_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(null=True, upload_to='profile/cover/%Y/%m/%d', validators=[utils.validators.SizeValidator(size=512)], verbose_name='Cover')),
                ('cover_thumbnail', models.URLField(blank=True, null=True, verbose_name='Cover thumbnail')),
                ('cover_transcoder', models.URLField(blank=True, null=True, verbose_name='Cover transcoder')),
                ('transcoder_job_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transcoder job id')),
                ('transcoder_job_success', models.BooleanField(default=False)),
                ('transcoder_uuid', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_files', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
