# Generated by Django 3.0.3 on 2020-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opted_in_for_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Whatsapp Messaging Enabled'),
        ),
    ]
