# Generated by Django 3.0 on 2020-01-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_coverfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_old_cover',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_thumbnail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_transcoder',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='transcoder_job_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='transcoder_job_success',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='transcoder_uuid',
        ),
    ]
