# Generated by Django 3.0.3 on 2020-09-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_objective_redirect_url'),
        ('users', '0022_profile_opted_in_for_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tags.CityProxy', verbose_name='City'),
        ),
    ]
