# Generated by Django 3.0.3 on 2020-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_opted_in_for_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intent',
            field=models.CharField(blank=True, choices=[('network', 'Network'), ('services', 'Services')], default='network', max_length=100, null=True, verbose_name='Intent'),
        ),
    ]
