# Generated by Django 3.0.3 on 2020-09-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_intent'),
        ('users', '0023_auto_20200908_1741'),
    ]

    operations = [
    ]
