# Generated by Django 3.0.3 on 2020-09-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20200911_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
    ]
