# Generated by Django 3.0.3 on 2021-02-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('score', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Not Employed'), (1, 'Startup'), (2, 'MNC'), (3, 'SME'), (4, 'Consultancy/Funds')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'High School'), (1, 'Undergraduate'), (2, 'Masters'), (3, 'MBA'), (4, 'PHD')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.CharField(blank=True, choices=[('Accounts', 'Accounts'), ('Agriculture', 'Agriculture'), ('AI', 'AI'), ('Bio', 'Bio'), ('Chemical', 'Chemical'), ('Computer', 'Computer'), ('Consulting', 'Consulting'), ('Data', 'Data'), ('Design', 'Design'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Electrical', 'Electrical'), ('Energy', 'Energy'), ('Environment', 'Environment'), ('Event', 'Event'), ('Fashion', 'Fashion'), ('Film', 'Film'), ('Financial', 'Financial'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('HR', 'HR'), ('Investor', 'Investor'), ('Law', 'Law'), ('Marketing', 'Marketing'), ('Mechanical', 'Mechanical'), ('Media', 'Media'), ('Mental Health', 'Mental Health'), ('Photography', 'Photography'), ('Politics', 'Politics'), ('Product', 'Product'), ('Real Estate', 'Real Estate'), ('Social', 'Social'), ('Startup', 'Startup'), ('Travel', 'Travel')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0-2'), (1, '3-5'), (2, '6-10'), (3, '11-15'), (4, '16-20'), (5, '21-30'), (6, '30+')], null=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('link', models.URLField(blank=True, max_length=128, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('base_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='users.BaseSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='new_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Source'),
        ),
    ]
