# Generated by Django 3.0.3 on 2021-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210218_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Not Employed'), (1, 'Startup'), (2, 'MNC'), (3, 'SME'), (4, 'Consultancy'), (5, 'Funds'), (6, 'Freelance')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.CharField(blank=True, choices=[('Accounts', 'Accounts'), ('Agriculture', 'Agriculture'), ('AI', 'AI'), ('Bio', 'Bio'), ('Chemical', 'Chemical'), ('Computer', 'Computer'), ('Consulting', 'Consulting'), ('Data', 'Data'), ('Design', 'Design'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Electrical', 'Electrical'), ('Energy', 'Energy'), ('Environment', 'Environment'), ('Event', 'Event'), ('Fashion', 'Fashion'), ('Film', 'Film'), ('Financial', 'Financial'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('HR', 'HR'), ('Investor', 'Investor'), ('Law', 'Law'), ('Marketing', 'Marketing'), ('Mechanical', 'Mechanical'), ('Media', 'Media'), ('Mental Health', 'Mental Health'), ('Photography', 'Photography'), ('Politics', 'Politics'), ('Product', 'Product'), ('Real Estate', 'Real Estate'), ('Social', 'Social'), ('Startup', 'Startup'), ('Travel', 'Travel'), ('Logistics', 'Logistics')], max_length=32, null=True),
        ),
    ]
