# Generated by Django 3.0.3 on 2021-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_faq'),
        ('users', '0028_auto_20210218_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_tag',
            field=models.ManyToManyField(to='tags.Tag', verbose_name='Tags'),
        ),
    ]
