# Generated by Django 3.0.3 on 2021-02-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_faq'),
        ('users', '0029_profile_new_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Not Employed'), (2, 'Startup'), (3, 'MNC'), (4, 'SME'), (5, 'Consultancy'), (6, 'Funds'), (7, 'Freelance')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'High School'), (2, 'Undergraduate'), (3, 'Masters'), (4, 'MBA'), (5, 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='new_tag',
            field=models.ManyToManyField(to='tags.Tag', verbose_name='New Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Consulting'), (2, 'AI, Data'), (3, 'Fashion'), (4, 'Politics, Social'), (5, 'Film, Media, Animation, Photography, Arts & Crafts'), (6, 'Education'), (7, 'Accounts, Financial, Banking, Insurance'), (8, 'F&B'), (9, 'Health'), (10, 'Mental Health'), (11, 'Computer Software'), (12, 'Investor'), (13, 'Law'), (14, 'Travel'), (15, 'Public Relations & Communications, Marketing, Writing & Editing'), (16, 'Chemical'), (17, 'Energy, Environment'), (18, 'HR')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '0 - 2 years'), (2, '3 - 5 years'), (3, '6 - 10 years'), (4, '11 - 15 years'), (5, '16-20 years'), (6, '21-30 years'), (7, '30+ years')], null=True),
        ),
    ]
