# Generated by Django 3.0.3 on 2021-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210223_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Consulting'), (2, 'AI, Data'), (3, 'Fashion'), (4, 'Politics, Social'), (5, 'Film, Media, Animation, Photography, Arts & Crafts'), (6, 'Education'), (7, 'Accounts, Financial, Banking, Insurance'), (8, 'Food, Restaurants'), (9, 'Health, Mental Health'), (10, 'Computer Software, Computer, Software'), (11, 'Investor'), (12, 'Law'), (13, 'Travel'), (14, 'Public Relations & Communications, Marketing, Writing & Editing'), (15, 'Chemical'), (16, 'Energy, Environment'), (17, 'HR')], null=True),
        ),
    ]
