# Generated by Django 3.0.3 on 2021-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210225_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Advisory & Consultancy'), (2, 'Agriculture'), (3, 'AI/ML/Blockchain'), (4, 'Airline/Aviation'), (5, 'Apparel & Fashion'), (6, 'Automotive & Transportation'), (7, 'Civic & Social Organization'), (8, 'Consumer Services'), (9, 'Cosmetics'), (10, 'Design & Media'), (11, 'E-commerce'), (12, 'Education'), (13, 'Entertainment'), (14, 'Offline Events'), (15, 'Financial Services'), (16, 'Food & Beverage'), (17, 'Gaming'), (18, 'Health, Wellness & Fitness'), (19, 'Hospitality'), (20, 'Information technology & Services'), (21, 'Investment Management  & Capital Markets'), (22, 'Legal sector'), (23, 'Leisure Travel & Tourism'), (24, 'Luxury & Consumer Goods'), (25, 'Marketing & Adverting'), (26, 'Packaging & Distribution'), (27, 'Pharmaceutical'), (28, 'Philanthropy'), (29, 'Real Estate'), (30, 'Renewables & Environment'), (31, 'Sports'), (32, 'Staffing & Recruiting'), (33, 'Community & Social'), (34, 'Technology,  Internet  & Software'), (35, 'Civil, Mechanical or Electrical Engineering'), (36, 'Logistics'), (60, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '0 - 2 years'), (2, '3 - 5 years'), (3, '6 - 10 years'), (4, '11 - 15 years'), (5, '16 - 20 years'), (6, '21 - 30 years'), (7, '30+ years')], null=True),
        ),
    ]
