# Generated by Django 3.0.3 on 2021-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210226_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Not Employed'), (2, 'Startup'), (3, 'MNC'), (4, 'SME'), (5, 'Consultancy'), (6, 'Fund'), (7, 'Freelance')], null=True),
        ),
    ]
