# Generated by Django 3.0.3 on 2021-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210317_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_introduction',
        ),
        migrations.AddField(
            model_name='profile',
            name='generated_introduction',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Auto Generated Introduction'),
        ),
    ]
