# Generated by Django 3.0.3 on 2021-06-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeviceInfo',
        ),
    ]
