# Generated by Django 3.0.3 on 2021-06-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_sourcewebsite_is_active'),
        ('users', '0036_delete_userdeviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aspiration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspiration_tag', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='companies_invested',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '0'), (2, '1-5'), (3, '5-10'), (4, '10-20'), (5, '10-20')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type_advised',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Not Employed'), (2, 'Startup'), (3, 'MNC'), (4, 'SME'), (5, 'Consultancy'), (6, 'Fund'), (7, 'Freelance')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1-10'), (2, '10-50'), (3, '50-100'), (4, '100-500'), (5, '500+')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_tag',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_intro_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Marketing'), (2, 'Graphic Design'), (3, 'Videography'), (4, 'UI/UX design'), (5, 'Software development')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stage_of_company',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Idea Stage'), (3, 'Seed Stage'), (4, 'Series A'), (5, 'Series B'), (6, 'Series C'), (7, 'Series D+')], null=True),
        ),
        migrations.CreateModel(
            name='ProfileExtraInfoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=800)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_meta', to='tags.Tag')),
            ],
        ),
    ]
