# Generated by Django 3.0.3 on 2021-06-29 14:32

from django.db import migrations

TAG_TO_EXTRA_INFO_MAP = {
    "Startup Founder": "{name} is the founder of {company_name}. The company is a {stage_of_company} startup, "
                       "operating in the {sector} sector. {name} has {years_of_experience} years of work experience & "
                       "has previously completed an {education_level} degree.",
    "Student": "{name} is a student. Currently pursuing an {education_level} degree. {name} is interested in "
               "the {sector} sector & eventually hopes to be a {aspiration}.",
    "SME Owner": "{name} is the owner of an SME by the name of {company_name} . The company, currently employees {"
                 "number_of_employees} people & is operating in the {sector} sector. {name} has {years_of_experience} "
                 "years of work experience & has previously completed an {education_level} degree.",
    "Financial Expert": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                        "currently consisting of {number_of_employees} employees & is operating in the {sector} "
                        "sector. {name} has previously completed an {education_level} degree.",
    "Lawyer": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
              "currently consisting of {number_of_employees} employees & is operating in the {sector} "
              "sector. {name} has previously completed an {education_level} degree.",
    "Marketing Expert": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                        "currently consisting of {number_of_employees} employees & is operating in the {sector} "
                        "sector. {name} has previously completed an {education_level} degree.",
    "Business Development Executive": "{name} is a financial expert, working with {company_name}. The company, "
                                      "is a {company_type}, currently consisting of {number_of_employees} employees & "
                                      "is operating in the {sector} sector. {name} has previously completed an"
                                      "{education_level} degree.",
    "Product Manager": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                       "currently consisting of {number_of_employees} employees & is operating in the {sector} "
                       "sector. {name} has previously completed an {education_level} degree. ",
    "Engineer": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                "currently consisting of {number_of_employees} employees & is operating in the {sector} sector. {"
                "name} has previously completed an {education_level} degree. ",
    "HR Executive": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                    "currently consisting of {number_of_employees} employees & is operating in the {sector} sector. {"
                    "name} has previously completed an {education_level} degree. ",
    "Designer": "{name} is a financial expert, working with {company_name}. The company, is a {company_type}, "
                "currently consisting of {number_of_employees} employees & is operating in the {sector} sector. {"
                "name} has previously completed an {education_level} degree.",
    "Business Advisor": "{name} is a Business Advisor, working in a {company_type}. {name} primarily advises {"
                        "company_type_advised} in the {sector} sector. {name} current has {years_of_experience} years "
                        "of work experience & has completed an {education_level} degree.",
    "Freelancer": "{name} is a freelancer, working in the {sector} sector. {name} works on {project_type} projects, "
                  "primarily with {company_type}. Previously {name} has completed a {education_level} degree.",
    "Startup Investor": "{name} is an investor, working with {company_name}. The company has a portfolio of {"
                        "companies_invested} companies & invests primarily at {stage_of_company} stage, "
                        "in the {sector} sector. {name} has {years_of_experience} years of work experience & has "
                        "completed a {education_level} degree.",
    "Intern": "{name} is an intern, working with {company_name}. The company operates in the {sector} sector. {name} "
              "works on {project_type} projects. {name} has completed a {education_level} degree.",
}

DEFAULT_EXTRA_INFO_STRING = "{name} is a {other_tag}, working with {company_name}. Company name operates in the {" \
                            "sector} sector.{name} has {years_of_experience} years of work experience & has completed " \
                            "a {education_level} degree."


def create_initial_extra_info_for_tags(apps, schema_editor):
    profile_extra_info = apps.get_model('users', 'ProfileExtraInfoMeta')
    tag_model = apps.get_model('tags', 'Tag')
    tags = tag_model.objects.all()
    all_profile_extra_list = []
    for tag in tags:
        question = TAG_TO_EXTRA_INFO_MAP.get(tag.name, DEFAULT_EXTRA_INFO_STRING)
        all_profile_extra_list.append(profile_extra_info(
            tag=tag,
            question=question,
        ))

    profile_extra_info.objects.bulk_create(all_profile_extra_list)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210629_1959'),
    ]

    operations = [
        migrations.RunPython(create_initial_extra_info_for_tags)
    ]
