# Generated by Django 3.0.3 on 2021-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210629_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_meeting_request',
            field=models.BooleanField(default=False),
        ),
    ]
