# Generated by Django 3.0.3 on 2021-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210913_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_url',
            field=models.URLField(blank=True, null=True, verbose_name='Showcase URL'),
        ),
    ]
