# Generated by Django 3.0.3 on 2021-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_profile_primary_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
