# Generated by Django 3.0.3 on 2022-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_sourcewebsite_is_active'),
        ('users', '0042_auto_20210923_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='New Tag'),
        ),
    ]
