# Generated by Django 3.0.3 on 2022-02-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20220209_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='generated_introduction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_intro_updated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag_line',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_service_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_source',
        ),
        migrations.RemoveField(
            model_name='user',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sms_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='source',
        ),
    ]
