# Generated by Django 3.0.3 on 2022-04-21 11:55

from django.db import migrations

def create_user_permission(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    user_permission = apps.get_model("users", "UserPermission")
    users = user_model.objects.all()
    for user in users:
        is_creator = bool(hasattr(user, "creator") and user.creator)
        user_permission.objects.get_or_create(
            user=user,
            allow_create_stream=is_creator
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_userpermission'),
    ]

    operations = [
        migrations.RunPython(create_user_permission, reverse_code=migrations.RunPython.noop),
    ]
