# Generated by Django 3.0.3 on 2022-05-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20220421_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='amount',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Yet to watch'), (2, 'Due'), (3, 'Paid'), (4, 'Cancelled')], default=1),
        ),
        migrations.CreateModel(
            name='ReferrerBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
