# Generated by Django 3.0.3 on 2022-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20220504_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
