# Generated by Django 3.0.3 on 2022-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20220627_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='metamask_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
