# Generated by Django 3.0.3 on 2022-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_profile_metamask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='show_viewer_count',
            field=models.BooleanField(default=False),
        ),
    ]
