# Generated by Django 2.2.7 on 2019-11-29 12:56
from django.db import migrations


def create_settings(apps, schema_editor):
    settings = apps.get_model('notifications', 'UserNotificationsSettings')
    users_models = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    users = users_models.objects.using(db_alias).all()
    for user in users:
        settings.objects.using(db_alias).get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_referral'),
    ]

    operations = [
        migrations.RunPython(create_settings, reverse_code=migrations.RunPython.noop),
    ]
