# Generated by Django 3.0 on 2020-01-13 14:17

from django.conf import settings
from django.db import migrations


def remove_reports(apps, schema_editor):
    reports = apps.get_model('posts', 'Report')
    reports.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20191213_1558'),
    ]

    operations = [
        migrations.RunPython(remove_reports, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'post')},
        ),
    ]
