# Generated by Django 3.0.2 on 2020-02-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200204_1712'),
        ('posts', '0004_auto_20200129_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_files', to='users.CoverFile', verbose_name='Cover File'),
        ),
    ]
