# Generated by Django 3.0.3 on 2022-01-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_payments', '0002_auto_20220113_1247'),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='crater_payments.Payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.PositiveIntegerField(choices=[(5, 'Payment Pending'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Cancelled')]),
        ),
    ]
