# Generated by Django 3.0.3 on 2022-01-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220113_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
    ]
