# Generated by Django 3.0.3 on 2022-02-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_auto_20220203_1745'),
        ('crater_rewards', '0005_auto_20220104_1519'),
        ('auctions', '0003_remove_bid_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='creator.Creator'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RewardAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='crater_rewards.Reward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.RewardAuction'),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
