# Generated by Django 3.0.3 on 2022-02-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220222_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='number_of_coins',
            new_name='quantity',
        ),
    ]
