# Generated by Django 3.0.3 on 2022-02-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0006_auto_20220222_2313'),
        ('auctions', '0005_auto_20220223_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardauction',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='crater_rewards.Reward'),
        ),
    ]
