FRESHCHAT_WHATSAPP_PROVIDER = "FRESHCHAT"
WATI_9501_WHATSAPP_PROVIDER = "WATI_9501"
WATI_8953_WHATSAPP_PROVIDER = "WATI_8964"

FRESHCHAT_WHATSAPP_PROVIDER_ENUM = 1
WATI_9501_WHATSAPP_PROVIDER_ENUM = 2
WATI_8953_WHATSAPP_PROVIDER_ENUM = 3


REMINDER_FOR_STREAM_ATTENDEES = "stream_reminder_attendee"
REMINDER_FOR_STREAM_FOLLOWERS = "stream_reminder_follower"
REMINDER_FOR_STREAM_CREATOR = "stream_reminder_creator"
CRATER_WELCOME_MESSAGE = "crater_welcome_message"
