# Generated by Django 3.0 on 2019-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Curated Article Tag',
                'verbose_name_plural': 'Curated Article Tags',
                'db_table': 'tags_article_tags',
            },
        ),
        migrations.CreateModel(
            name='MasterClassTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Master Class Tag',
                'verbose_name_plural': 'Master Class Tags',
                'db_table': 'tags_masterclass_tag',
            },
        ),
    ]
