# Generated by Django 3.0 on 2019-12-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_articletag_masterclasstag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
    ]
