# Generated by Django 3.0 on 2019-12-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_company_funding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': 'Curated Article Tags'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Funding', 'verbose_name_plural': 'Fundings'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='masterclasstag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Master Class Tag', 'verbose_name_plural': 'Master Class Tags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'User Tag', 'verbose_name_plural': 'User Tags'},
        ),
        migrations.AddField(
            model_name='articletag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funding',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterclasstag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
