# Generated by Django 3.0 on 2019-12-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191221_0805'),
        ('tags', '0005_auto_20191221_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProxy',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['order', 'name'],
            },
            bases=('locations.city',),
        ),
        migrations.CreateModel(
            name='WorkCityProxy',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.City')),
            ],
            options={
                'verbose_name': 'Work City',
                'verbose_name_plural': 'Work Cities',
                'ordering': ['order', 'name'],
            },
            bases=('locations.city',),
        ),
    ]
