# Generated by Django 3.0 on 2019-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_cityproxy_workcityproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curated Article Tag',
                'verbose_name_plural': '9. Event Tags',
                'db_table': 'tags_events',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': '8. Curated Article Tags'},
        ),
        migrations.AlterModelOptions(
            name='cityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'City', 'verbose_name_plural': '1. Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': '6. Companies'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Funding', 'verbose_name_plural': '5. Fundings'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Industry', 'verbose_name_plural': '4. Industries'},
        ),
        migrations.AlterModelOptions(
            name='masterclasstag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Master Class Tag', 'verbose_name_plural': '7. Master Class Tags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'User Tag', 'verbose_name_plural': '3. User Tags'},
        ),
        migrations.AlterModelOptions(
            name='workcityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Work City', 'verbose_name_plural': '2. Work Cities'},
        ),
    ]
