# Generated by Django 3.0 on 2019-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20191221_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Source Website',
                'verbose_name_plural': 'Source Websites',
                'db_table': 'tags_websites',
            },
        ),
    ]
