# Generated by Django 3.0 on 2019-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_sourcewebsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': '08. Curated Article Tags'},
        ),
        migrations.AlterModelOptions(
            name='cityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'City', 'verbose_name_plural': '01. Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': '06. Companies'},
        ),
        migrations.AlterModelOptions(
            name='eventtag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': '09. Event Tags'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Funding', 'verbose_name_plural': '05. Fundings'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Industry', 'verbose_name_plural': '04. Industries'},
        ),
        migrations.AlterModelOptions(
            name='masterclasstag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Master Class Tag', 'verbose_name_plural': '07. Master Class Tags'},
        ),
        migrations.AlterModelOptions(
            name='sourcewebsite',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Source Website', 'verbose_name_plural': '10. Source Websites'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'User Tag', 'verbose_name_plural': '03. User Tags'},
        ),
        migrations.AlterModelOptions(
            name='workcityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Work City', 'verbose_name_plural': '02. Work Cities'},
        ),
        migrations.AddField(
            model_name='sourcewebsite',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
