# Generated by Django 3.0.2 on 2020-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20191221_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclasstag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
