# Generated by Django 3.0.3 on 2020-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_auto_20200203_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('business_strategy', 'Business Strategy'), ('current_affairs', 'Current Affairs'), ('design_and_branding', 'Design & Branding'), ('finance_and_investments', 'Finance & Investments'), ('funding_and_vc', 'Funding & Venture Capital'), ('law_and_policy', 'Law & Policy'), ('marketing_and_advertising', 'Marketing & Advertising'), ('software_and_product', 'Software & Product Development')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
