# Generated by Django 3.0.3 on 2020-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'ordering': ['name'], 'verbose_name': 'User Interests', 'verbose_name_plural': '03. User Interests'},
        ),
        migrations.AddField(
            model_name='interests',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
