# Generated by Django 3.0.3 on 2020-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'User Objective',
                'verbose_name_plural': 'User Objectives',
                'ordering': ['name'],
            },
        ),
    ]
