# Generated by Django 3.0.3 on 2020-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect URL'),
        ),
    ]
