# Generated by Django 3.0.3 on 2020-07-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_auto_20200723_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'ordering': ['name'], 'verbose_name': 'User Interests', 'verbose_name_plural': '11. User Interests'},
        ),
    ]
