# Generated by Django 3.0.3 on 2020-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_objective_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='intent',
            field=models.CharField(blank=True, choices=[('network', 'Network'), ('services', 'Services')], default='network', max_length=100, null=True, verbose_name='Intent'),
        ),
    ]
