# Generated by Django 3.0.3 on 2021-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': 'Curated Article Tags'},
        ),
        migrations.AlterModelOptions(
            name='cityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='eventtag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Curated Article Tag', 'verbose_name_plural': 'Event Tags'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Funding', 'verbose_name_plural': 'Fundings'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'ordering': ['name'], 'verbose_name': 'User Interests', 'verbose_name_plural': 'User Interests'},
        ),
        migrations.AlterModelOptions(
            name='masterclasstag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Master Class Tag', 'verbose_name_plural': 'Master Class Tags'},
        ),
        migrations.AlterModelOptions(
            name='sourcewebsite',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Source Website', 'verbose_name_plural': 'Source Websites'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'User Tag', 'verbose_name_plural': 'User Tags'},
        ),
        migrations.AlterModelOptions(
            name='workcityproxy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Work City', 'verbose_name_plural': 'Work Cities'},
        ),
        migrations.AddField(
            model_name='sourcewebsite',
            name='image',
            field=models.ImageField(default=None, upload_to='articles/%Y/%m/%d', verbose_name='Source Image'),
            preserve_default=False,
        ),
    ]
