# Generated by Django 3.0.3 on 2021-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_auto_20210429_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='Source Image'),
        ),
    ]
