# Generated by Django 3.0.3 on 2021-05-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_auto_20210429_1554_squashed_0018_auto_20210429_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcewebsite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
