# Generated by Django 3.0.2 on 2020-01-21 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.BooleanField(default=True)),
                ('post_comments', models.BooleanField(default=True)),
                ('post_likes', models.BooleanField(default=True)),
                ('new_videos_posted', models.BooleanField(default=True)),
                ('new_articles_posted', models.BooleanField(default=True)),
                ('new_events_created', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
