# Generated by Django 3.0.3 on 2020-04-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='new_post_created',
            field=models.BooleanField(default=True),
        ),
    ]
