# Generated by Django 3.0.3 on 2020-04-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_file_file'),
        ('notifications', '0003_usernotificationssettings_new_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.Like', verbose_name='Like'),
        ),
    ]
