DEFAULT_CURRENCY = "₹"

DEFAULT_CAPTURE_METHOD = "manual"
DEFAULT_PAYMENT_METHOD_TYPES = ["card"]

WEBHOOK_EVENT_TYPE_CHARGE_SUCCEEDED = "charge.succeeded"
WEBHOOK_EVENT_TYPE_CHARGE_CAPTURED = "charge.captured"
