# Generated by Django 3.0.3 on 2022-10-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crater_auth', '0003_auto_20221025_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=32)),
                ('sid', models.CharField(max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=16, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crater_auth.PhoneOtp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
