# Generated by Django 3.0 on 2020-01-03 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['id'], 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='attachmentfile',
            options={'ordering': ['id'], 'verbose_name': 'Attachment File', 'verbose_name_plural': 'Attachment Files'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderservice',
            options={'ordering': ['id'], 'verbose_name': 'Order Service', 'verbose_name_plural': 'Order Services'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='order_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order.OrderService', verbose_name='Order service'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='order_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.OrderService', verbose_name='Order service'),
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('accepted', 'Accepted')], default='pending', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_funding_requests', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Funding Request',
                'verbose_name_plural': 'Funding Requests',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='funding_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order.FundingRequest', verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='funding_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.FundingRequest', verbose_name='Funding Request'),
        ),
    ]
