# Generated by Django 3.0.2 on 2020-01-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200103_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='funding_request',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='order_service',
        ),
        migrations.RemoveField(
            model_name='attachmentfile',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
        migrations.DeleteModel(
            name='FundingRequest',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderService',
        ),
    ]
