# Generated by Django 3.0.2 on 2020-01-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0011_auto_20191227_0832'),
        ('order', '0003_auto_20200113_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('complete', 'Complete')], default='created', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_quotas', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_quotas', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuotaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='order.Quota', verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Order Service',
                'verbose_name_plural': 'Order Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('accepted', 'Accepted')], default='pending', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_funding_requests', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Funding Request',
                'verbose_name_plural': 'Funding Requests',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.Attachment', verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Attachment File',
                'verbose_name_plural': 'Attachment Files',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='funding_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.FundingRequest', verbose_name='Funding Request'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='quota_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.QuotaService', verbose_name='Order service'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Question')),
                ('text', models.TextField(max_length=800, verbose_name='Text')),
                ('funding_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order.FundingRequest', verbose_name='Answers')),
                ('quota_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='order.QuotaService', verbose_name='Order service')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
    ]
