# Generated by Django 3.0.2 on 2020-01-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200113_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='funding_request',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='quota_service',
        ),
        migrations.RemoveField(
            model_name='attachmentfile',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='quotaservice',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='quotaservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
        migrations.DeleteModel(
            name='FundingRequest',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.DeleteModel(
            name='QuotaService',
        ),
    ]
