# Generated by Django 3.0.2 on 2020-01-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200114_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='revisions',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Revisions'),
        ),
    ]
