# Generated by Django 3.0.2 on 2020-01-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200114_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteservice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='order.Order', verbose_name='Order'),
        ),
    ]
