# Generated by Django 3.0.2 on 2020-01-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200114_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='funding_request',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='quote_service',
        ),
        migrations.RemoveField(
            model_name='attachmentfile',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creative_exchange_response',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
        migrations.DeleteModel(
            name='FundingRequest',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteService',
        ),
    ]
