# Generated by Django 3.0.2 on 2020-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200114_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank='True', max_length=800, verbose_name='Note from Provider'),
        ),
        migrations.AddField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, max_length=800, verbose_name='Note from Provider'),
        ),
    ]
