# Generated by Django 3.0.2 on 2020-01-15 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0008_auto_20200115_1033'),
        ('services', '0011_auto_20191227_0832'),
        ('order', '0012_auto_20200114_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creative_exchange_response',
        ),
        migrations.AddField(
            model_name='quote',
            name='additional_text',
            field=models.TextField(blank=True, max_length=800, verbose_name='Additional text'),
        ),
        migrations.AddField(
            model_name='quote',
            name='exchange_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='creative_exchange.ExchangeRequest', verbose_name='Exchange Request'),
        ),
        migrations.AddField(
            model_name='quote',
            name='followers',
            field=models.PositiveIntegerField(null=True, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='quote',
            name='includes',
            field=models.TextField(blank=True, max_length=800, verbose_name='Includes and Process'),
        ),
        migrations.AddField(
            model_name='quote',
            name='require',
            field=models.TextField(blank=True, max_length=800, verbose_name='I require'),
        ),
        migrations.AddField(
            model_name='quote',
            name='year_of_experience',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provided', 'Provided'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='quote_pending', max_length=100),
        ),
    ]
