# Generated by Django 3.0.2 on 2020-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200115_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provided', 'Provided'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=100),
        ),
    ]
