# Generated by Django 3.0.2 on 2020-01-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200116_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingrequest',
            options={'ordering': ['order_field', '-created'], 'verbose_name': 'Funding Request', 'verbose_name_plural': 'Funding Requests'},
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='order_field',
            field=models.IntegerField(default=1),
        ),
    ]
