# Generated by Django 3.0.2 on 2020-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200117_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_field', '-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['order_field', '-created'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_field',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quote',
            name='order_field',
            field=models.IntegerField(default=1),
        ),
    ]
