# Generated by Django 3.0.2 on 2020-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200120_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_file',
            field=models.FileField(null=True, upload_to='order/completed_file/%Y/%m/%d', verbose_name='Completed File'),
        ),
    ]
