# Generated by Django 3.0.2 on 2020-01-23 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_completed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Text'),
        ),
    ]
