# Generated by Django 3.0.2 on 2020-01-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200123_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='text',
            new_name='review_text',
        ),
    ]
