# Generated by Django 3.0.2 on 2020-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequest',
            name='comments',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
