# Generated by Django 3.0.2 on 2020-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_fundingrequest_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('done', 'Done'), ('complete', 'Complete')], default='created', max_length=100),
        ),
    ]
