# Generated by Django 3.0.3 on 2020-03-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200219_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
