# Generated by Django 3.0.3 on 2020-03-31 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_review_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='revisions',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Revisions'),
        ),
    ]
