# Generated by Django 3.0.3 on 2020-04-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200331_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Time start')),
                ('time_end', models.TimeField(verbose_name='Time end')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_preferences', to='order.Order', verbose_name='Order')),
            ],
        ),
    ]
