# Generated by Django 3.0.3 on 2020-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_orderpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='additional_text',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Additional text'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='includes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Includes and Process'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Note from Provider'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='require',
            field=models.TextField(blank=True, max_length=2000, verbose_name='I require'),
        ),
    ]
