# Generated by Django 3.0.3 on 2020-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200415_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='additional_text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Additional text'),
        ),
    ]
