# Generated by Django 3.0.3 on 2021-03-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations.google', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevent',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
