GROUP_PRIVACY_PUBLIC = "public"
GROUP_PRIVACY_PRIVATE = "private"

GROUP_MEDIUM_AUDIO = "audio"
GROUP_MEDIUM_AUDIO_VIDEO = "audio & video"
GROUP_MEDIUM_CHAT = "chat"

DEFAULT_MAX_SPEAKERS = 6

INVITE_STATUS_PENDING = "pending"
INVITE_STATUS_ACCEPTED = "accepted"
INVITE_STATUS_DECLINED = "declined"

INVITE_TYPE_SPEAKER = "speaker"
INVITE_TYPE_ATTENDEE = "attendee"

REQUEST_STATUS_PENDING = "pending"
REQUEST_STATUS_ACCEPTED = "accepted"
REQUEST_STATUS_DECLINED = "declined"

EXTRA_EMAIL_FOR_INTRO_VERIFICATION = "hello@worknetwork.in"
MEETING_COMMUNICATION_FROM_EMAIL = "meetings@worknetwork.in"
MEETING_REPLY_EMAIL = "vivan@worknetwork.in"
GROUP_CONVERSATION_INTRODUCTION_TEMPLATE = "Group Conversation Introduction"
GROUP_CONVERSATION_FEEDBACK_TEMPLATE = "Group Conversation Feedback"

DEFAULT_TOPIC_NAME = "Default"