# Generated by Django 3.0 on 2019-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('unknown', 'No Decision')], default='unknown', max_length=16, verbose_name='Status'),
        ),
    ]
