# Generated by Django 3.0 on 2019-12-19 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_industry'),
        ('services', '0002_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.CharField(blank=True, choices=[('less_1_year', 'Less than 1 year'), ('1-2', '1-2 years'), ('3-4', '3-4 years'), ('5-7', '5-7 years'), ('8-10', '8-10 years')], max_length=100, null=True)),
                ('bar_council', models.CharField(max_length=100, verbose_name='Bar council / CA identification')),
                ('followers', models.PositiveIntegerField(null=True, verbose_name='Combined followers on social networks')),
                ('industries', models.ManyToManyField(related_name='user_infos', to='tags.Industry')),
                ('services', models.ManyToManyField(related_name='user_infos', to='services.Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_services_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Service Info',
                'verbose_name_plural': 'User Service Info',
            },
        ),
    ]
