# Generated by Django 3.0 on 2019-12-19 13:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_company_funding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_userserviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceinfo',
            name='bar_council',
            field=models.CharField(max_length=100, null=True, verbose_name='Bar council / CA identification'),
        ),
        migrations.AlterField(
            model_name='userserviceinfo',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('less_1_year', 'Less than 1 year'), ('1-2', '1-2 years'), ('3-4', '3-4 years'), ('5-7', '5-7 years'), ('8-10', '8-10 years')], max_length=100, null=True, verbose_name='Years of Experience'),
        ),
        migrations.CreateModel(
            name='InvestorServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.CharField(blank=True, choices=[('less_1_year', 'Less than 1 year'), ('1-2', '1-2 years'), ('3-4', '3-4 years'), ('5-7', '5-7 years'), ('8-10', '8-10 years')], max_length=100, null=True, verbose_name='Years of Experience')),
                ('number_of_startups', models.PositiveIntegerField(null=True, verbose_name='Number of Startups')),
                ('connect_with_us', models.BooleanField(default=False, verbose_name='Connect with us')),
                ('process', models.TextField(max_length=800, verbose_name='Process')),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=3)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=3)),
                ('companies', models.ManyToManyField(to='tags.Company', verbose_name='Companies can connect to')),
                ('kind_of_funding', models.ManyToManyField(to='tags.Funding', verbose_name='Kind of Funding')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_services_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Investor Info',
                'verbose_name_plural': 'User Investor Infos',
            },
        ),
    ]
