# Generated by Django 3.0 on 2019-12-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191219_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserviceinfo',
            name='generate_business',
            field=models.BooleanField(default=False, verbose_name='Generate business'),
        ),
        migrations.AddField(
            model_name='userserviceinfo',
            name='professional_service_provider',
            field=models.BooleanField(default=False, verbose_name='Professional service provider'),
        ),
    ]
