# Generated by Django 3.0 on 2019-12-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191223_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorserviceinfo',
            name='reach_out',
            field=models.BooleanField(default=False, verbose_name='Reach out'),
        ),
        migrations.AddField(
            model_name='investorserviceinfo',
            name='understand',
            field=models.BooleanField(default=False, verbose_name='Understand'),
        ),
    ]
