# Generated by Django 3.0 on 2019-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20191223_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.FileField(null=True, upload_to='category/photo/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
