# Generated by Django 3.0 on 2019-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to='category/photo/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
