# Generated by Django 3.0 on 2019-12-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20191224_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCategoryProxy',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Category')),
            ],
            options={
                'verbose_name': 'Marketing Category',
                'verbose_name_plural': 'Marketing Categories',
                'ordering': ['name'],
            },
            bases=('services.category',),
        ),
        migrations.CreateModel(
            name='ProfessionalCategoryProxy',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Category')),
            ],
            options={
                'verbose_name': 'Professional Category',
                'verbose_name_plural': 'Professional Categories',
                'ordering': ['name'],
            },
            bases=('services.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.CharField(choices=[('professional', 'Professional'), ('marketing', 'Marketing')], default='professional', max_length=100, verbose_name='Direction'),
        ),
    ]
