# Generated by Django 3.0 on 2019-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20191224_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Rating'),
        ),
    ]
