# Generated by Django 3.0 on 2019-12-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
