# Generated by Django 3.0.2 on 2020-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20191227_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceinfo',
            name='bar_council',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bar council / CA identification'),
        ),
    ]
