# Generated by Django 3.0.2 on 2020-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200123_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
    ]
