# Generated by Django 3.0.2 on 2020-01-28 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20200123_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorserviceinfo',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='investorserviceinfo',
            name='process',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='investorserviceinfo',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=3),
        ),
    ]
