# Generated by Django 3.0.2 on 2020-02-03 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200128_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=3),
        ),
    ]
