# Generated by Django 3.0.2 on 2020-02-04 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200203_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3),
        ),
    ]
