# Generated by Django 3.0.3 on 2020-04-15 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200204_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorserviceinfo',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='investorserviceinfo',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3),
        ),
    ]
