# Generated by Django 3.0.3 on 2020-05-07 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20200415_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='revision',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Revision'),
        ),
    ]
