# Generated by Django 3.0.3 on 2020-05-27 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20200507_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='revision',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='service',
            name='timeline',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Timeline'),
        ),
        migrations.AlterField(
            model_name='userserviceinfo',
            name='followers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Combined followers on social networks'),
        ),
    ]
