# Generated by Django 3.0.3 on 2020-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20200527_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceinfo',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='user_infos', to='services.Service'),
        ),
    ]
