# Generated by Django 3.0.3 on 2022-09-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crater_payments', '0003_auto_20220901_2103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crater_rewards', '0008_auto_20220304_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('payment_type', models.PositiveIntegerField(choices=[(1, 'Upi'), (2, 'Learn')], default=2)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='crater_rewards.Reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardSaleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Payment Pending'), (2, 'Payment Confirmed'), (3, 'Payment Declined')], default=1)),
                ('is_processed', models.BooleanField(default=False)),
                ('payment_type', models.PositiveIntegerField(choices=[(1, 'Upi'), (2, 'Learn')], default=2)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_log', to='crater_payments.Payment')),
                ('reward_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.RewardSale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
