# Generated by Django 3.0.3 on 2022-09-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_usertoken'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsalelog',
            name='token_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_log', to='tokens.UserTokenLog'),
        ),
    ]
