# Generated by Django 3.0.3 on 2022-09-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rewardsalelog_token_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsale',
            name='show_in_store',
            field=models.BooleanField(default=True),
        ),
    ]
