# Generated by Django 3.0.3 on 2022-09-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rewardsalelog_token_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsalelog',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
