# Generated by Django 3.0.3 on 2022-09-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rewardsale_show_in_store'),
        ('sales', '0003_rewardsalelog_processed_at'),
    ]

    operations = [
    ]
