from django.conf import settings

# Freshchat Whatsapp details.
FRESHCHAT_BASE_URL = settings.FRESHCHAT_BASE_URL
FRESHCHAT_APP_ID = settings.FRESHCHAT_APP_ID
FRESHCHAT_ACCESS_TOKEN = settings.FRESHCHAT_ACCESS_TOKEN

FRESHCHAT_MESSAGING_PHONE_NUMBER = settings.FRESHCHAT_MESSAGING_PHONE_NUMBER
FRESHCHAT_WHATSAPP_NAMESPACE = settings.FRESHCHAT_WHATSAPP_NAMESPACE

MEETING_CONFIRMATION_FRESHCHAT_TEMPLATE = "confirmation_of_appointment"
MEETING_REMINDER_FRESHCHAT_TEMPLATE = "appointment_reminder"
MEETING_OPT_IN_REMINDER_TEMPLATE = "confirming_meeting"
FRESHCHAT_DEFAULT_PROVIDER = "whatsapp"

# Freshchat API responses.
FRESHCHAT_STATUS_SUCCESS = 200
FRESHCHAT_STATUS_CREATED = 201
FRESHCHAT_STATUS_ACCEPTED = 202

# Possible message statuses.
FRESHCHAT_MESSAGE_ACCEPTED = 'ACCEPTED'
FRESHCHAT_MESSAGE_SENT = 'SENT'
FRESHCHAT_MESSAGE_DELIVERED = 'DELIVERED'
FRESHCHAT_MESSAGE_FAILED = 'FAILED'
FRESHCHAT_MESSAGE_IN_PROGRESS = 'IN_PROGRESS'

# If message response status is in these, it means that
# message is yet to be sent to the user.
FRESHCHAT_MESSAGE_PENDING_STATUSES = [
    FRESHCHAT_MESSAGE_ACCEPTED,
    FRESHCHAT_MESSAGE_IN_PROGRESS
]

# If message response status is in these, it means that
# message is successfully sent to the user.
FRESHCHAT_MESSAGE_SUCCESS_STATUSES = [
    FRESHCHAT_MESSAGE_DELIVERED,
    FRESHCHAT_MESSAGE_SENT
]

# If message response status is in these, it means that
# message sending has failed.
FRESHCHAT_MESSAGE_FAILURE_STATUSES = [
    FRESHCHAT_MESSAGE_FAILED,
]
