from django.conf import settings

FRESHCHAT_BASE_URL = settings.FRESHCHAT_BASE_URL
FRESHCHAT_APP_ID = settings.FRESHCHAT_APP_ID
FRESHCHAT_ACCESS_TOKEN = settings.FRESHCHAT_ACCESS_TOKEN

FRESHCHAT_MESSAGING_PHONE_NUMBER = settings.FRESHCHAT_MESSAGING_PHONE_NUMBER
FRESHCHAT_WHATSAPP_NAMESPACE = settings.FRESHCHAT_WHATSAPP_NAMESPACE


MEETING_REMINDER_FRESHCHAT_TEMPLATE = "appointment_reminder"
FRESHCHAT_DEFAULT_PROVIDER = "whatsapp"
