# Generated by Django 3.0 on 2019-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191211_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_work',
            field=models.BooleanField(default=False, verbose_name='Is work'),
        ),
    ]
