# Generated by Django 3.0 on 2019-12-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_is_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order', 'name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
