PAYMENT_STATUS_PENDING_ENUM = 1
PAYMENT_STATUS_SUCCESS_ENUM = 2
PAYMENT_STATUS_FAILED_ENUM = 3

PAYMENT_STATUS_PENDING = "Pending"
PAYMENT_STATUS_SUCCESS = "Success"
PAYMENT_STATUS_FAILED = "Failed"

PAYMENT_GATEWAY_STRIPE_ENUM = 1
PAYMENT_GATEWAY_CREATOR_UPI_ENUM = 2

PAYMENT_GATEWAY_STRIPE = "Stripe"
PAYMENT_GATEWAY_CREATOR_UPI = "Creator Upi"


PAYMENT_TYPE_TOKEN_ENUM = 1
PAYMENT_TYPE_ONLINE_ENUM = 2

PAYMENT_TYPE_TOKEN = "Token"
PAYMENT_TYPE_ONLINE = "Online"

