# Generated by Django 3.0 on 2019-12-17 14:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('membership', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=255, verbose_name='Membership')),
                ('terms_and_condition', models.BooleanField(default=True, verbose_name='Terms and condition')),
                ('stripe_customer_id', models.CharField(max_length=400, verbose_name='Stripe Customer ID')),
                ('card_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Stripe card data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
