# Generated by Django 3.0 on 2019-12-18 09:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='card_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Stripe card data'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='stripe_customer_id',
            field=models.CharField(max_length=400, null=True, verbose_name='Stripe Customer ID'),
        ),
    ]
