# Generated by Django 3.0.2 on 2020-01-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0020_order_is_paid'),
        ('payment', '0002_auto_20191218_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('direction', models.CharField(choices=[('in', 'Income'), ('out', 'Outcome')], default='in', max_length=100)),
                ('charge_stripe_id', models.CharField(max_length=400, null=True, verbose_name='Charge Stripe Id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('refund', 'Refund'), ('transferred', 'Transferred')], max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.Order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created'],
            },
        ),
    ]
