# Generated by Django 3.0.2 on 2020-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='membership',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=255, verbose_name='Membership'),
        ),
    ]
