# Generated by Django 3.0.2 on 2020-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_subscription_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank account name'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank account number'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank ifsc code'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank name'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch name'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='funds_recipient',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=255, verbose_name='Funds Recipient'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='pan_card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pan card number'),
        ),
    ]
