# Generated by Django 3.0.3 on 2020-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_stripepaymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='membership_aggreed',
            field=models.BooleanField(default=True, verbose_name='Membership aggreed'),
        ),
    ]
