# Generated by Django 3.0.3 on 2022-02-04 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crater_payments', '0002_auto_20220113_1247'),
        ('creator', '0017_creator_point_of_contact'),
        ('crater_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crater_payments.Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Bid'), (2, 'Redemption'), (3, 'Auction')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercoinholding',
            unique_together={('user', 'coin')},
        ),
    ]
