# Generated by Django 3.0.3 on 2022-02-25 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0006_auto_20220225_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crater_exchange', '0002_auto_20220225_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('redeemed_quantity', models.PositiveIntegerField(default=0)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_holding', to='crater_rewards.Reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_holding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reward')},
            },
        ),
    ]
