# Generated by Django 3.0.3 on 2022-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_exchange', '0003_userreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Bid'), (2, 'Redemption'), (3, 'Auction'), (4, 'Sale')]),
        ),
    ]
