# Generated by Django 3.0.3 on 2022-09-08 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crater_rewards', '0008_auto_20220304_1629'),
        ('crater_exchange', '0004_auto_20220901_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='crater_rewards.Reward'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
