# Generated by Django 3.0.3 on 2021-07-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule', models.CharField(choices=[('phone_price_validation', 'Phone_Price_Validation'), ('introduction_validation', 'Introduction_Validation'), ('linkedin_url_validation', 'Linkedin_Url_Validation'), ('education_level_validation', 'Education_Level_Validation')], max_length=64)),
                ('result', models.PositiveIntegerField(choices=[(1, 'Score Too High'), (2, 'Score Too Low')])),
                ('is_validated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Validation',
                'verbose_name_plural': 'User Validations',
                'unique_together': {('user', 'rule', 'result')},
            },
        ),
    ]
