# Generated by Django 3.0.3 on 2022-09-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0047_auto_20220914_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='conversations.Category')),
                ('streams', models.ManyToManyField(blank=True, related_name='squads', to='conversations.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
