# Generated by Django 3.0 on 2019-12-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'User Request', 'verbose_name_plural': 'User Requests'},
        ),
        migrations.AlterModelTable(
            name='userrequest',
            table='user_requests',
        ),
    ]
