# Generated by Django 3.0 on 2020-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191216_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover',
            field=models.ImageField(null=True, upload_to='groups/cover/%Y/%m/%d/', verbose_name='Cover Image'),
        ),
    ]
