# Generated by Django 3.0 on 2020-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order'], 'verbose_name': 'Community Location', 'verbose_name_plural': 'Community Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
