# Generated by Django 3.0 on 2020-01-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200110_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Community Location', 'verbose_name_plural': 'Community Locations'},
        ),
    ]
