# Generated by Django 3.0 on 2020-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200110_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(null=True, upload_to='groups/icons/%Y/%m/%d/', verbose_name='Group Icon'),
        ),
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.ImageField(null=True, upload_to='locations/icons/%Y/%m/%d/', verbose_name='Location Icon'),
        ),
    ]
