# Generated by Django 3.0.3 on 2022-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('crater_welcome_message', 'crater_welcome_message'), ('stream_reminder_attendee', 'stream_reminder_attendee'), ('stream_reminder_follower', 'stream_reminder_follower'), ('stream_reminder_creator', 'stream_reminder_creator')], max_length=132)),
                ('provider', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'FRESHCHAT'), (2, 'WATI_9501'), (3, 'WATI_8964')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
