# Generated by Django 3.0.3 on 2022-09-08 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
