# Generated by Django 3.0.3 on 2022-09-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20220909_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenlog',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_log', to='tokens.TokenTransaction'),
        ),
    ]
