# Generated by Django 3.0 on 2019-12-13 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_city_is_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Date')),
                ('start', models.TimeField(verbose_name='Start Time')),
                ('end', models.TimeField(verbose_name='End Time')),
                ('is_free', models.BooleanField(verbose_name='Free')),
                ('is_rsvp', models.BooleanField(verbose_name='RSVP Required')),
                ('capacity', models.PositiveIntegerField(null=True, verbose_name='Venue capacity')),
                ('state', models.CharField(choices=[('upcoming', 'Upcoming'), ('going', 'Going'), ('past', 'Past')], default='upcoming', max_length=16, verbose_name='State')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Asia/Kolkata')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locations.City')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'resources_events',
                'ordering': ('-date', '-start'),
            },
        ),
        migrations.CreateModel(
            name='RSVPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvpds', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rsvpds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVPD',
                'verbose_name_plural': 'RSVPD',
                'db_table': 'resources_rsvpd',
            },
        ),
    ]
