# Generated by Django 3.0 on 2019-12-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(null=True, upload_to='events/%Y/%m/%d', verbose_name='Cover photo'),
        ),
    ]
