# Generated by Django 3.0 on 2019-12-16 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvpd',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='rsvpd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='rsvpd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='rsvpd',
            table='resources_participants',
        ),
    ]
