# Generated by Django 3.0 on 2019-12-18 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20191216_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvpd',
            unique_together={('event', 'user')},
        ),
    ]
