# Generated by Django 3.0 on 2019-12-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20191221_0851'),
        ('events', '0004_auto_20191218_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tags.EventTag', verbose_name='Event Tag'),
        ),
    ]
