# Generated by Django 3.0.2 on 2020-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_rsvp',
            new_name='is_rsvp_required',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='3128  Hill Croft Farm Road', max_length=255, verbose_name='Event Address'),
            preserve_default=False,
        ),
    ]
