# Generated by Django 3.0 on 2020-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20191221_0915'),
        ('creative_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('days', models.PositiveIntegerField(null=True, verbose_name='Days')),
                ('require', models.BooleanField(default=False, verbose_name='Project Completion')),
                ('cover_image', models.ImageField(upload_to='exchange_request/cover/%Y/%m/%d/', verbose_name='Cover')),
                ('description', models.TextField(max_length=800, verbose_name='Description')),
                ('special_requirement', models.TextField(max_length=800, verbose_name='Special Requirements')),
                ('additional_information', models.TextField(max_length=800, verbose_name='Additional Information')),
                ('extended_price', models.PositiveIntegerField(verbose_name='Extended Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='creative_exchange.ExchangeCategory', verbose_name='Exchange')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='tags.CityProxy', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exchange_request/files/%Y/%m/%d/', verbose_name='Image')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='creative_exchange.ExchangeRequest', verbose_name='Request')),
            ],
        ),
    ]
