# Generated by Django 3.0 on 2020-01-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creative_exchange', '0002_exchangerequest_requestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
