# Generated by Django 3.0 on 2020-01-10 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creative_exchange', '0004_auto_20200110_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerequest',
            options={'verbose_name': 'Exchange Request', 'verbose_name_plural': 'Exchange Requests'},
        ),
        migrations.CreateModel(
            name='ExchangeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('timeline', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Timeline')),
                ('revisions', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Revisions')),
                ('year_of_experience', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Years of experience')),
                ('followers', models.PositiveIntegerField(null=True, verbose_name='Followers')),
                ('includes', models.TextField(max_length=800, verbose_name='Includes and Process')),
                ('additional_text', models.TextField(max_length=800, verbose_name='Additional text')),
                ('require', models.TextField(max_length=800, verbose_name='I require')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='creative_exchange.ExchangeRequest', verbose_name='Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_responses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Exchange Response',
                'verbose_name_plural': 'Exchange Responses',
            },
        ),
    ]
