# Generated by Django 3.0 on 2020-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0005_auto_20200110_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
