# Generated by Django 3.0 on 2020-01-11 10:03

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0006_exchangerequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeresponse',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='exchangeresponse',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
