# Generated by Django 3.0.2 on 2020-01-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0007_auto_20200111_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeresponse',
            name='request',
        ),
        migrations.RemoveField(
            model_name='exchangeresponse',
            name='user',
        ),
    ]
