# Generated by Django 3.0.2 on 2020-01-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0008_auto_20200115_1033'),
        ('order', '0013_auto_20200115_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeResponse',
        ),
    ]
