# Generated by Django 3.0.2 on 2020-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0009_delete_exchangeresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='exchange_request/cover/%Y/%m/%d/', verbose_name='Cover'),
        ),
    ]
