# Generated by Django 3.0.2 on 2020-01-31 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0010_auto_20200131_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='days',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='extended_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Extended Price'),
        ),
    ]
