# Generated by Django 3.0.3 on 2020-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0011_auto_20200131_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='additional_information',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='special_requirement',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Special Requirements'),
        ),
    ]
