# Generated by Django 3.0.3 on 2020-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0012_auto_20200317_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecategory',
            name='photo',
            field=models.ImageField(null=True, upload_to='category/photo/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
