# Generated by Django 3.0.3 on 2020-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_exchange', '0013_exchangecategory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='exchange_request/cover/%Y/%m/%d/', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Description'),
        ),
    ]
