# Generated by Django 3.0.3 on 2020-07-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0011_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('week_start_date', models.DateField(blank=True, null=True, verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(blank=True, null=True, verbose_name='Week End Date')),
                ('is_registration_open', models.BooleanField(default=True, verbose_name='Registration Open')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMeetingPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number_of_meetings', models.PositiveIntegerField(default=1)),
                ('objective', models.CharField(choices=[('meet_interesting_people', 'Meet interesting people'), ('brainstorm_with_peers', 'Brainstorm with Peers'), ('business_development', 'Business Development'), ('start_a_company', 'Start a Company'), ('mentor_people', 'Mentor People'), ('find_mentors', 'Find Mentors')], max_length=255)),
                ('interests', models.ManyToManyField(to='tags.Interests', verbose_name='Interests')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='meetings.Meeting', verbose_name='Meetings')),
                ('time_slots', models.ManyToManyField(to='meetings.TimeSlot', verbose_name='Time Slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='available_time_slots',
            field=models.ManyToManyField(related_name='meetings', to='meetings.TimeSlot', verbose_name='Available Slots'),
        ),
    ]
