# Generated by Django 3.0.3 on 2020-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='registration_start_date',
            field=models.DateField(null=True, verbose_name='Registration Start Date'),
        ),
        migrations.AlterField(
            model_name='usermeetingpreference',
            name='objective',
            field=models.CharField(choices=[('meet_interesting_people', 'Meet Interesting People'), ('brainstorm_with_peers', 'Brainstorm with Peers'), ('business_development', 'Business Development'), ('start_a_company', 'Start a Company'), ('mentor_people', 'Mentor People'), ('find_mentors', 'Find Mentors')], max_length=255),
        ),
    ]
