# Generated by Django 3.0.3 on 2020-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeetingpreference',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='usermeetingpreference',
            name='time_slots',
            field=models.ManyToManyField(to='meetings.TimeSlot', verbose_name='Time Slots'),
        ),
    ]
