# Generated by Django 3.0.3 on 2020-08-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200729_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='MeetingConfig',
        ),
        migrations.AlterField(
            model_name='usermeetingpreference',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='meetings.MeetingConfig', verbose_name='Meeting Config'),
        ),
    ]
