# Generated by Django 3.0.3 on 2020-08-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_auto_20200806_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='type',
            field=models.CharField(choices=[('1:1', '1:1')], default='1:1', max_length=64),
        ),
        migrations.AlterField(
            model_name='meetingconfig',
            name='available_time_slots',
            field=models.ManyToManyField(related_name='meeting_configs', to='meetings.TimeSlot', verbose_name='Available Slots'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('meeting_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetings.MeetingConfig', verbose_name='Meeting Config')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organiser')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetings.TimeSlot', verbose_name='Time Slot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
