# Generated by Django 3.0.3 on 2020-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20200825_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
