# Generated by Django 3.0.3 on 2020-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0015_tag_is_active'),
        ('meetings', '0006_meeting_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Meeting Interest',
                'verbose_name_plural': 'User Meeting Interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Meeting Objective',
                'verbose_name_plural': 'User Meeting Objectives',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organiser',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting End Time'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting Start Time'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeetingpreference',
            name='interests',
            field=models.ManyToManyField(to='tags.Interests', verbose_name='Meeting Interests'),
        ),
    ]
