# Generated by Django 3.0.3 on 2020-09-17 12:04
from __future__ import unicode_literals

from django.db import migrations

OBJECTIVE_CHOICES = [
    ('meet_interesting_people', 'Meet Interesting People'),
    ('brainstorm_with_peers', 'Brainstorm with Peers'),
    ('business_development', 'Business Development'),
    ('start_a_company', 'Start a Company'),
    ('mentor_people', 'Mentor People'),
    ('find_mentors', 'Find Mentors')
]


def populate_meeting_interest_and_profiles(apps, schema_editor):

    tag_interest_model = apps.get_model('tags', 'Interests')
    meeting_interest_model = apps.get_model('meetings', 'Interest')
    meeting_objective_model = apps.get_model('meetings', 'Objective')

    meeting_interests = []
    for tag_interest in tag_interest_model.objects.all():
        meeting_interest = meeting_interest_model(
            name=tag_interest.name,
            icon=tag_interest.icon
        )
        meeting_interests.append(meeting_interest)

    meeting_objectives = []
    for key, name in OBJECTIVE_CHOICES:
        meeting_objective = meeting_objective_model(
            name=name,
        )
        meeting_objectives.append(meeting_objective)

    # Bulk creating in one go.
    meeting_interest_model.objects.bulk_create(meeting_interests)
    meeting_objective_model.objects.bulk_create(meeting_objectives)


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20200917_1729'),
    ]

    operations = [
        migrations.RunPython(populate_meeting_interest_and_profiles),
    ]
