# Generated by Django 3.0.3 on 2020-09-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20200917_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeetingpreference',
            name='objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Objective', verbose_name='Meeting Objective'),
        ),
        migrations.AlterField(
            model_name='usermeetingpreference',
            name='interests',
            field=models.ManyToManyField(to='meetings.Interest', verbose_name='Meeting Interests'),
        ),
    ]
