# Generated by Django 3.0.3 on 2020-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20200917_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeetingpreference',
            name='objective',
            field=models.CharField(blank=True, choices=[('meet_interesting_people', 'Meet Interesting People'), ('brainstorm_with_peers', 'Brainstorm with Peers'), ('business_development', 'Business Development'), ('start_a_company', 'Start a Company'), ('mentor_people', 'Mentor People'), ('find_mentors', 'Find Mentors')], max_length=255, null=True),
        ),
    ]
