# Generated by Django 3.0.3 on 2020-10-05 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0010_auto_20201003_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingConfig',
            new_name='Config',
        ),
        migrations.RenameModel(
            old_name='UserMeetingPreference',
            new_name='MeetingPreference',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_config',
            new_name='config',
        ),
    ]
