# Generated by Django 3.0.3 on 2020-10-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meetings_model_renames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingpreference',
            name='objectives',
        ),
        migrations.AddField(
            model_name='meetingpreference',
            name='objectives',
            field=models.ManyToManyField(blank=True, null=True, to='meetings.Objective', verbose_name='Meeting Objective'),
        ),
    ]
