# Generated by Django 3.0.3 on 2020-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_mettings_objectives_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpreference',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='meetings.Objective', verbose_name='Meeting Objective'),
        ),
    ]
