# Generated by Django 3.0.3 on 2020-10-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20201021_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='type',
            field=models.CharField(choices=[('looking_for', 'Looking For'), ('looking-to', 'Looking To')], default='looking_for', max_length=255),
        ),
    ]
