# Generated by Django 3.0.3 on 2020-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_objective_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.CharField(choices=[('looking_for', 'Looking For'), ('looking_to', 'Looking To')], default='looking_for', max_length=255),
        ),
    ]
