# Generated by Django 3.0.3 on 2020-11-26 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0015_auto_20201110_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('pending', 'Pending'), ('not_attending', 'Not Attending'), ('reschedule', 'Reschedule')], default='pending', max_length=255, verbose_name='Status')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='meetings.Meeting', verbose_name='Meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rsvps', to=settings.AUTH_USER_MODEL, verbose_name='Meeting Participant')),
            ],
            options={
                'unique_together': {('meeting', 'participant')},
            },
        ),
    ]
