# Generated by Django 3.0.3 on 2020-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_meetingrsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrsvp',
            name='status',
            field=models.CharField(choices=[('attending', 'Attending'), ('pending', 'Pending'), ('not_attending', 'Not_Attending'), ('reschedule', 'Reschedule')], default='pending', max_length=255, verbose_name='Status'),
        ),
    ]
