# Generated by Django 3.0.3 on 2020-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_auto_20201203_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('rescheduled', 'Rescheduled')], default='pending', max_length=32, verbose_name='Meeting Status'),
        ),
    ]
