# Generated by Django 3.0.3 on 2020-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpreference',
            name='number_of_meetings_per_month',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
