# Generated by Django 3.0.3 on 2020-12-17 10:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0019_meetingpreference_number_of_meetings_per_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingpreference',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('time_slots', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), size=3)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending_Approval'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending_approval', max_length=32)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('new_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_from', to='meetings.Meeting', verbose_name='New Meeting')),
                ('old_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='meetings.Meeting', verbose_name='Old Meeting')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='Request By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
