# Generated by Django 3.0.3 on 2021-01-13 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0020_auto_20201217_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingpreference',
            name='objective',
        ),
        migrations.AlterUniqueTogether(
            name='reschedulerequest',
            unique_together={('old_meeting', 'requested_by')},
        ),
    ]
