# Generated by Django 3.0.3 on 2020-12-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0020_auto_20201217_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time_slot',
        ),
    ]
