# Generated by Django 3.0.3 on 2021-01-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0021_auto_20210113_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meeting Interest', 'verbose_name_plural': 'Meeting Interests'},
        ),
        migrations.AlterModelOptions(
            name='meetingpreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meeting Preference', 'verbose_name_plural': 'Meeting Preferences'},
        ),
        migrations.AlterModelOptions(
            name='meetingrsvp',
            options={'verbose_name': 'Meeting RSVP', 'verbose_name_plural': "Meeting RSVP's"},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meeting Objective', 'verbose_name_plural': 'Meeting Objectives'},
        ),
        migrations.AlterModelOptions(
            name='reschedulerequest',
            options={'verbose_name': 'Reschedule Request', 'verbose_name_plural': 'Reschedule Requests'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='MeetingTimeSlot',
        ),
    ]
