# Generated by Django 3.0.3 on 2021-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0022_auto_20210115_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedulerequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
