# Generated by Django 3.0.3 on 2021-03-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('meetings', '0023_reschedulerequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpreference',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='conversations.Topic'),
        ),
    ]
