# Generated by Django 3.0.3 on 2021-08-25 08:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0024_meetingpreference_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('time_slots', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), size=3)),
                ('selected_time_slot', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending_Approval'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending_approval', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_requested', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Request',
                'verbose_name_plural': 'Meeting Requests',
            },
        ),
    ]
