# Generated by Django 3.0.3 on 2021-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0025_meetingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
