# Generated by Django 3.0 on 2019-12-18 11:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_articletag_masterclasstag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('teacher', models.CharField(max_length=255, verbose_name='Teacher Name')),
                ('position', models.CharField(max_length=255, verbose_name='Teacher Position')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover', models.FileField(null=True, upload_to='masterclasses/%Y/%m/%d', validators=[utils.validators.SizeValidator(size=512)], verbose_name='Cover')),
                ('tags', models.ManyToManyField(to='tags.MasterClassTag')),
            ],
            options={
                'verbose_name': 'Master Class',
                'verbose_name_plural': 'Master Classes',
                'db_table': 'resources_masterclasses',
                'ordering': ['-created'],
            },
        ),
    ]
