# Generated by Django 3.0 on 2019-12-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclass',
            old_name='teacher',
            new_name='author',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Times viewed'),
        ),
    ]
