# Generated by Django 3.0.2 on 2020-01-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_rating'),
        ('masterclasses', '0002_auto_20191219_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterclasses', to='users.CoverFile', verbose_name='Cover File'),
        ),
    ]
