GROUP_REMINDER_NOTIFICATION = "conversation_reminder"
GROUP_CONVERSATION_CREATED = "conversation_created"
OPTIN_NOTIFICATION = "optin"
GROUP_LIVE_NOTIFICATION = "conversation_live"
GROUP_CONVERSATION_INVITE = "conversation_invite"
STREAM_GOING_LIVE_NOTIFICATION = "stream_going_live"
STREAM_REMINDER_NOTIFICATION = "stream_reminder"

DEFAULT_NOTIFICATION_SMALL_ICON = "ic_notification"
DEFAULT_NOTIFICATION_ANDROID_ACCENT_COLOR = "FF283845"

OBJECT_TYPE_UPCOMING_MEETING = "upcoming_meeting"
OBJECT_TYPE_CONVERSATION = "conversation"
OBJECT_TYPE_CREATE_CONVERSATION = "create_conversation"

MAX_PLAYER_IDS_FOR_BULK_NOTIFICATIONS = 2000
