import datetime

TRANSACTION_TYPE_ACQUIRED = "acquired"
TRANSACTION_TYPE_REDEEMED = "redeemed"

TRANSACTION_TYPE_ACQUIRED_ENUM = 1
TRANSACTION_TYPE_REDEEMED_ENUM = 2


LEARN_TOKEN_START_DATE = datetime.datetime(2022, 7, 27)
