# Generated by Django 3.0.3 on 2020-06-05 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from points.constants import POINTS_RULES


def create_points_rule(apps, schema_editor):
    PointsRule = apps.get_model('points', 'PointsRule')
    db_alias = schema_editor.connection.alias
    for rule in POINTS_RULES:
        PointsRule.objects.using(db_alias).get_or_create(
            key=rule['key'],
            desc=rule['desc'],
            points_value=rule['points_value']
        )


def create_user_points(apps, schema_editor):
    Users = apps.get_model('users', 'User')
    UserPoints = apps.get_model('points', 'UserPoints')
    db_alias = schema_editor.connection.alias
    all_users = Users.objects.using(db_alias).all()
    for user in all_users:
        UserPoints.objects.using(db_alias).get_or_create(
            user=user,
            points=0
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField()),
                ('desc', models.CharField(max_length=120)),
                ('points_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
            },
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('base_points_value', models.IntegerField(null=True, verbose_name='Base Points')),
                ('base_factor', models.IntegerField(default=1, verbose_name='Base Factor')),
                ('bonus_points_value', models.IntegerField(null=True, verbose_name='Bonus Points')),
                ('bonus_factor', models.IntegerField(default=1, verbose_name='Bonus Factor')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule', to='points.PointsRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_user_points),
        migrations.RunPython(create_points_rule)
    ]
