SECTOR_TO_NEW_SECTOR_MAP = {
    "Airline/Aviation": "",
    "Community & Social": "",
    "Renewables & Environment": "",
    "Logistics": "",
    "Education": "",
    "Advisory & Consultancy": "",
    "Investment Management  & Capital Markets": "",
    "Legal sector": "",
    "Design & Media": "",
    "Entertainment": "",
    "Marketing & Adverting": "",
    "Real Estate": "",
    "Staffing & Recruiting": "",
    "Consumer Services": "",
    "Leisure Travel & Tourism": "",
    "AI/ML/Blockhain": "",
    "Automotive & Transportation": "",
    "Agriculture": "",
    "Technology & Internet": "",
    "Other": "",
    "Health": "",
    "Information technology & Services": "",
    "E-commerce": "",
    "Financial Services": "",
    "Sports": "",
}
