# Generated by Django 3.0.3 on 2020-08-27 11:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshchatuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freshchat_user', to=settings.AUTH_USER_MODEL, verbose_name='FreshChat User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_id', models.CharField(blank=True, max_length=512, null=True)),
                ('message_id', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED')], max_length=32, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshchat_messages', to=settings.AUTH_USER_MODEL, verbose_name='FreshChat Messages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
