# Generated by Django 3.0.3 on 2020-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshchat', '0002_auto_20200827_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED')], max_length=32, null=True),
        ),
    ]
