# Generated by Django 3.0.3 on 2021-10-01 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshchat', '0003_auto_20200827_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshchat_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
