from users import choices as user_constants

EDUCATION_LEVEL_SCORES = {
    user_constants.EDUCATION_LEVEL_HIGH_SCHOOL_ENUM: 30,
    user_constants.EDUCATION_LEVEL_UNDERGRADUATE_ENUM: 60,
    user_constants.EDUCATION_LEVEL_MASTERS_ENUM: 70,
    user_constants.EDUCATION_LEVEL_MBA_ENUM: 80,
    user_constants.EDUCATION_LEVEL_PHD_ENUM: 100
}

TAG_TO_EXPERIENCE_SCORES = {
    "Startup Founder": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 40,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 70
    },
    "SME Owner": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 40,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 80
    },
    "Startup Investor": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Financial Expert": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Engineer": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 40,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Business Development Executive": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Marketing Expert": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Business Advisor": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 40,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Product Manager": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 40,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Lawyer": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Designer": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 20,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Student/Intern": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 10,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 10
      },
    "Senior Executive": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 60,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "HR Executive": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Other": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    }
}


TAG_TO_COMPANY_TYPE_SCORES = {
    "Startup Founder": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 100,
        user_constants.COMPANY_TYPE_MNC_ENUM: 30,
        user_constants.COMPANY_TYPE_SME_ENUM: 60,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 30,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 15,
    },
    "SME Owner": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 20,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 60,
        user_constants.COMPANY_TYPE_MNC_ENUM: 30,
        user_constants.COMPANY_TYPE_SME_ENUM: 100,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 30,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 15,
    },
    "Startup Investor": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 30,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 50,
        user_constants.COMPANY_TYPE_MNC_ENUM: 30,
        user_constants.COMPANY_TYPE_SME_ENUM: 30,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 70,
        user_constants.COMPANY_TYPE_FUND_ENUM: 100,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 15,
    },
    "Financial Expert": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 30,
        user_constants.COMPANY_TYPE_MNC_ENUM: 80,
        user_constants.COMPANY_TYPE_SME_ENUM: 50,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 60,
        user_constants.COMPANY_TYPE_FUND_ENUM: 70,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 40,
    },
    "Engineer": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 100,
        user_constants.COMPANY_TYPE_MNC_ENUM: 40,
        user_constants.COMPANY_TYPE_SME_ENUM: 30,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 60,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 50,
    },
    "Business Development Executive": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 30,
        user_constants.COMPANY_TYPE_MNC_ENUM: 100,
        user_constants.COMPANY_TYPE_SME_ENUM: 50,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 40,
        user_constants.COMPANY_TYPE_FUND_ENUM: 40,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 30,
    },
    "Marketing Expert": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 80,
        user_constants.COMPANY_TYPE_MNC_ENUM: 100,
        user_constants.COMPANY_TYPE_SME_ENUM: 60,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 50,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 40,
    },
    "Business Advisor": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 20,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 40,
        user_constants.COMPANY_TYPE_MNC_ENUM: 80,
        user_constants.COMPANY_TYPE_SME_ENUM: 60,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 100,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 60,
    },
    "Product Manager": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 20,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 100,
        user_constants.COMPANY_TYPE_MNC_ENUM: 80,
        user_constants.COMPANY_TYPE_SME_ENUM: 40,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 60,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 50,
    },
    "Lawyer": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 20,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 30,
        user_constants.COMPANY_TYPE_MNC_ENUM: 60,
        user_constants.COMPANY_TYPE_SME_ENUM: 40,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 100,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 40,
    },
    "Designer": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 20,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 80,
        user_constants.COMPANY_TYPE_MNC_ENUM: 60,
        user_constants.COMPANY_TYPE_SME_ENUM: 30,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 100,
        user_constants.COMPANY_TYPE_FUND_ENUM: 15,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 60,
    },
    "Student/Intern": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 10,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 10,
        user_constants.COMPANY_TYPE_MNC_ENUM: 10,
        user_constants.COMPANY_TYPE_SME_ENUM: 10,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 10,
        user_constants.COMPANY_TYPE_FUND_ENUM: 10,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 10,
    },
    "Senior Executive": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 30,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 40,
        user_constants.COMPANY_TYPE_MNC_ENUM: 100,
        user_constants.COMPANY_TYPE_SME_ENUM: 60,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 80,
        user_constants.COMPANY_TYPE_FUND_ENUM: 40,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 60,
      },
    "HR Executive": {
        user_constants.EXPERIENCE_ONE_TO_TWO_YEARS_ENUM: 30,
        user_constants.EXPERIENCE_THREE_TO_FIVE_YEARS_ENUM: 50,
        user_constants.EXPERIENCE_SIX_TO_TEN_YEARS_ENUM: 70,
        user_constants.EXPERIENCE_ELEVEN_TO_FIFTEEN_YEARS_ENUM: 80,
        user_constants.EXPERIENCE_SIXTEEN_TO_TWENTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_TWENTY_ONE_TO_THIRTY_YEARS_ENUM: 100,
        user_constants.EXPERIENCE_THIRTY_PLUS_YEARS_ENUM: 100
    },
    "Other": {
        user_constants.COMPANY_TYPE_NOT_EMPLOYED_ENUM: 15,
        user_constants.COMPANY_TYPES_START_UP_ENUM: 30,
        user_constants.COMPANY_TYPE_MNC_ENUM: 60,
        user_constants.COMPANY_TYPE_SME_ENUM: 50,
        user_constants.COMPANY_TYPE_CONSULTANCY_ENUM: 40,
        user_constants.COMPANY_TYPE_FUND_ENUM: 40,
        user_constants.COMPANY_TYPE_FREELANCE_ENUM: 30,
    }
}

TAG_TO_TAG_SCORES = {
    'HR Executive': {
        'Startup Founder': 10,
        'SME Owner': 20,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 10,
        'Business Development Executive': 70,
        'Marketing Expert': 50,
        'Business Advisor': 20,
        'Product Manager': 10,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 70,
        'HR Executive': 70
    },
    'Startup Founder': {
        'Startup Founder': 100,
        'SME Owner': 50,
        'Startup Investor': 100,
        'Financial Expert': 20,
        'Engineer': 30,
        'Business Development Executive': 10,
        'Marketing Expert': 40,
        'Business Advisor': 60,
        'Product Manager': 40,
        'Lawyer': 10,
        'Designer': 20,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 10,
        'HR Executive': 10
    },
    'SME Owner': {
        'Startup Founder': 50,
        'SME Owner': 70,
        'Startup Investor': 20,
        'Financial Expert': 40,
        'Engineer': 10,
        'Business Development Executive': 20,
        'Marketing Expert': 40,
        'Business Advisor': 80,
        'Product Manager': 10,
        'Lawyer': 40,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 60,
        'Other': 20,
        'HR Executive': 20
    },
    'Startup Investor': {
        'Startup Founder': 100,
        'SME Owner': 20,
        'Startup Investor': 50,
        'Financial Expert': 40,
        'Engineer': 10,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 60,
        'Product Manager': 10,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 70,
        'Other': 10,
        'HR Executive': 10
    },
    'Financial Expert': {
        'Startup Founder': 20,
        'SME Owner': 70,
        'Startup Investor': 50,
        'Financial Expert': 40,
        'Engineer': 10,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 50,
        'Product Manager': 10,
        'Lawyer': 40,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 10,
        'HR Executive': 10
    },
    'Engineer': {
        'Startup Founder': 30,
        'SME Owner': 10,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 70,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 10,
        'Product Manager': 80,
        'Lawyer': 10,
        'Designer': 50,
        'Student/Intern': 0,
        'Senior Executive': 10,
        'Other': 10,
        'HR Executive': 10
    },
    'Business Development Executive': {
        'Startup Founder': 10,
        'SME Owner': 20,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 10,
        'Business Development Executive': 70,
        'Marketing Expert': 50,
        'Business Advisor': 20,
        'Product Manager': 10,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 70,
        'HR Executive': 70
    },
    'Marketing Expert': {
        'Startup Founder': 40,
        'SME Owner': 40,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 10,
        'Business Development Executive': 50,
        'Marketing Expert': 30,
        'Business Advisor': 30,
        'Product Manager': 10,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 50,
        'HR Executive': 50
    },
    'Business Advisor': {
        'Startup Founder': 60,
        'SME Owner': 80,
        'Startup Investor': 60,
        'Financial Expert': 50,
        'Engineer': 10,
        'Business Development Executive': 20,
        'Marketing Expert': 30,
        'Business Advisor': 10,
        'Product Manager': 30,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 80,
        'Other': 20,
        'HR Executive': 20
    },
    'Product Manager': {
        'Startup Founder': 40,
        'SME Owner': 10,
        'Startup Investor': 10,
        'Financial Expert': 80,
        'Engineer': 80,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 30,
        'Product Manager': 100,
        'Lawyer': 10,
        'Designer': 50,
        'Student/Intern': 0,
        'Senior Executive': 10,
        'Other': 10,
        'HR Executive': 10
    },
    'Lawyer': {
        'Startup Founder': 10,
        'SME Owner': 40,
        'Startup Investor': 10,
        'Financial Expert': 40,
        'Engineer': 10,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 10,
        'Product Manager': 10,
        'Lawyer': 0,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 10,
        'HR Executive': 10
    },
    'Designer': {
        'Startup Founder': 20,
        'SME Owner': 10,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 50,
        'Business Development Executive': 10,
        'Marketing Expert': 10,
        'Business Advisor': 10,
        'Product Manager': 50,
        'Lawyer': 10,
        'Designer': 70,
        'Student/Intern': 0,
        'Senior Executive': 10,
        'Other': 10,
        'HR Executive': 10
    },
    'Student/Intern': {
        'Startup Founder': 0,
        'SME Owner': 0,
        'Startup Investor': 0,
        'Financial Expert': 0,
        'Engineer': 0,
        'Business Development Executive': 0,
        'Marketing Expert': 0,
        'Business Advisor': 0,
        'Product Manager': 0,
        'Lawyer': 0,
        'Designer': 0,
        'Student/Intern': 100,
        'Senior Executive': 0,
        'Other': 0,
        'HR Executive': 0
    },
    'Senior Executive': {
        'Startup Founder': 40,
        'SME Owner': 60,
        'Startup Investor': 70,
        'Financial Expert': 40,
        'Engineer': 10,
        'Business Development Executive': 40,
        'Marketing Expert': 40,
        'Business Advisor': 80,
        'Product Manager': 10,
        'Lawyer': 40,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 100,
        'Other': 40,
        'HR Executive': 40
    },
    'Other': {
        'Startup Founder': 10,
        'SME Owner': 20,
        'Startup Investor': 10,
        'Financial Expert': 10,
        'Engineer': 10,
        'Business Development Executive': 70,
        'Marketing Expert': 50,
        'Business Advisor': 20,
        'Product Manager': 10,
        'Lawyer': 10,
        'Designer': 10,
        'Student/Intern': 0,
        'Senior Executive': 40,
        'Other': 70,
        'HR Executive': 70
    }
}

TAG_TO_INTEREST_SCORES = {
    'Startup Founder': {
        'Startup Founders': 100,
        'SME Owners': 80,
        'Startup Investors': 60,
        'Financial Experts': 30,
        'Engineers': 50,
        'Business Development Executives': 10,
        'Marketing Experts': 30,
        'Business Advisors': 50,
        'Product Managers': 60,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 60,
        'HR Executives': 10
    },
    'SME Owner': {
        'Startup Founders': 80,
        'SME Owners': 100,
        'Startup Investors': 50,
        'Financial Experts': 30,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 30,
        'Business Advisors': 60,
        'Product Managers': 50,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 70,
        'HR Executives': 10
    },
    'Startup Investor': {
        'Startup Founders': 70,
        'SME Owners': 70,
        'Startup Investors': 100,
        'Financial Experts': 70,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 70,
        'Product Managers': 10,
        'Lawyers': 50,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 80,
        'HR Executives': 10
    },
    'Financial Expert': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 70,
        'Financial Experts': 100,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 80,
        'Product Managers': 10,
        'Lawyers': 60,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 40,
        'HR Executives': 10
    },
    'Engineer': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 100,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 10,
        'Product Managers': 70,
        'Lawyers': 10,
        'Designers': 40,
        'Students/Interns': 10,
        'Senior Executives': 10,
        'HR Executives': 10
    },
    'Business Development Executive': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 10,
        'Business Development Executives': 100,
        'Marketing Experts': 70,
        'Business Advisors': 10,
        'Product Managers': 10,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 50,
        'Senior Executives': 10,
        'HR Executives': 100
    },
    'Marketing Expert': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 10,
        'Business Development Executives': 70,
        'Marketing Experts': 100,
        'Business Advisors': 40,
        'Product Managers': 10,
        'Lawyers': 10,
        'Designers': 50,
        'Students/Interns': 10,
        'Senior Executives': 10,
        'HR Executives': 70
    },
    'Business Advisor': {
        'Startup Founders': 60,
        'SME Owners': 70,
        'Startup Investors': 60,
        'Financial Experts': 60,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 50,
        'Business Advisors': 100,
        'Product Managers': 10,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 70,
        'HR Executives': 10
    },
    'Product Manager': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 70,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 10,
        'Product Managers': 100,
        'Lawyers': 10,
        'Designers': 50,
        'Students/Interns': 10,
        'Senior Executives': 10,
        'HR Executives': 10
    },
    'Lawyer': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 10,
        'Product Managers': 10,
        'Lawyers': 100,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 50,
        'HR Executives': 10
    },
    'Designer': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 60,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 10,
        'Product Managers': 50,
        'Lawyers': 10,
        'Designers': 100,
        'Students/Interns': 10,
        'Senior Executives': 10,
        'HR Executives': 10
    },
    'Students/Intern': {
        'Startup Founders': 0,
        'SME Owners': 0,
        'Startup Investors': 0,
        'Financial Experts': 0,
        'Engineers': 0,
        'Business Development Executives': 0,
        'Marketing Experts': 0,
        'Business Advisors': 0,
        'Product Managers': 0,
        'Lawyers': 0,
        'Designers': 0,
        'Students/Interns': 100,
        'Senior Executives': 0,
        'HR Executives': 0
    },
    'Senior Executive': {
        'Startup Founders': 60,
        'SME Owners': 70,
        'Startup Investors': 60,
        'Financial Experts': 50,
        'Engineers': 10,
        'Business Development Executives': 60,
        'Marketing Experts': 50,
        'Business Advisors': 70,
        'Product Managers': 10,
        'Lawyers': 40,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 100,
        'HR Executives': 60
    },
    'Other': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 10,
        'Business Development Executives': 10,
        'Marketing Experts': 10,
        'Business Advisors': 10,
        'Product Managers': 10,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 10,
        'Senior Executives': 10,
        'HR Executives': 10
    },
    'HR Executive': {
        'Startup Founders': 10,
        'SME Owners': 10,
        'Startup Investors': 10,
        'Financial Experts': 10,
        'Engineers': 10,
        'Business Development Executives': 100,
        'Marketing Experts': 70,
        'Business Advisors': 10,
        'Product Managers': 10,
        'Lawyers': 10,
        'Designers': 10,
        'Students/Interns': 50,
        'Senior Executives': 10,
        'HR Executives': 100
    }
}

SECTOR_TO_SECTOR_SCORES = {
    "Agriculture": {
        "Agriculture": 100,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 60,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 80,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "AI/ML/Blockchain": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 100,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 60,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 70,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Airline/Aviation": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 100,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Apparel & Fashion": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 100,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 60,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 50,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 60,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Automotive & Transportation": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 100,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 70,
        "Other": 0
    },
    "Civic & Social Organization": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 100,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 80,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Consumer Services": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 100,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 60,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Cosmetics": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 100,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Design & Media": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 100,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 80,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 60,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "E-commerce": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 50,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 100,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 60,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 60,
        "Other": 0
    },
    "Education": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 100,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Entertainment": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 80,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 100,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Offline Events": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 100,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 60,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Financial Services": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 100,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 80,
        "Legal sector": 50,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 60,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Food & Beverage": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 100,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Gaming": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 100,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 50,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Health, Wellness & Fitness": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 100,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Hospitality": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 100,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Information technology & Services": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 100,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Investment Management  & Capital Markets": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 80,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 100,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 70,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Legal sector": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 50,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 100,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Leisure Travel & Tourism": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 100,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Luxury & Consumer Goods": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 60,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 50,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 100,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Marketing & Adverting": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 60,
        "Cosmetics": 0,
        "Design & Media": 60,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 60,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 100,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Packaging & Distribution": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 60,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 100,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 60,
        "Other": 0
    },
    "Pharmaceutical": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 100,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Philanthropy": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 80,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 100,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Real Estate": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 60,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 70,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 100,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Renewables & Environment": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 100,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Sports": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 50,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 100,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Staffing & Recruiting": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 100,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Community & Social": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 100,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Technology,  Internet  & Software": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 70,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 100,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    },
    "Civil, Mechanical or Electrical Engineering": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 100,
        "Logistics": 0,
        "Other": 0
    },
    "Logistics": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 70,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 60,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 60,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 100,
        "Other": 0
    },
    "Other": {
        "Agriculture": 0,
        "AI/ML/Blockchain": 0,
        "Airline/Aviation": 0,
        "Apparel & Fashion": 0,
        "Automotive & Transportation": 0,
        "Civic & Social Organization": 0,
        "Consumer Services": 0,
        "Cosmetics": 0,
        "Design & Media": 0,
        "E-commerce": 0,
        "Education": 0,
        "Entertainment": 0,
        "Offline Events": 0,
        "Financial Services": 0,
        "Food & Beverage": 0,
        "Gaming": 0,
        "Health, Wellness & Fitness": 0,
        "Hospitality": 0,
        "Information technology & Services": 0,
        "Investment Management  & Capital Markets": 0,
        "Legal sector": 0,
        "Leisure Travel & Tourism": 0,
        "Luxury & Consumer Goods": 0,
        "Marketing & Adverting": 0,
        "Packaging & Distribution": 0,
        "Pharmaceutical": 0,
        "Philanthropy": 0,
        "Real Estate": 0,
        "Renewables & Environment": 0,
        "Sports": 0,
        "Staffing & Recruiting": 0,
        "Community & Social": 0,
        "Technology,  Internet  & Software": 0,
        "Civil, Mechanical or Electrical Engineering": 0,
        "Logistics": 0,
        "Other": 0
    }
}
