# Generated by Django 3.0 on 2019-12-16 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Source Website',
                'verbose_name_plural': 'Source Websites',
                'db_table': 'resources_websites',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'resources_tags',
            },
        ),
        migrations.CreateModel(
            name='CuratedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('text', models.TextField(verbose_name='Text')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_articles', to='curated_articles.Tag', verbose_name='Tag')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_articles', to='curated_articles.SourceWebsite', verbose_name='Source Website')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'resources_articles',
                'ordering': ('-created',),
            },
        ),
    ]
