# Generated by Django 3.0 on 2019-12-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedarticle',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
