# Generated by Django 3.0 on 2019-12-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_articletag_masterclasstag'),
        ('curated_articles', '0002_auto_20191218_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedarticle',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_articles', to='tags.ArticleTag', verbose_name='Tag'),
        ),
    ]
