# Generated by Django 3.0 on 2019-12-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0003_curatedarticle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedarticle',
            name='website',
        ),
        migrations.DeleteModel(
            name='SourceWebsite',
        ),
    ]
