# Generated by Django 3.0 on 2019-12-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20191221_0915'),
        ('curated_articles', '0004_auto_20191221_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedarticle',
            name='website_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_articles', to='tags.SourceWebsite', verbose_name='Source Website'),
        ),
    ]
