# Generated by Django 3.0.3 on 2020-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0005_curatedarticle_website_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedarticle',
            name='website_url',
            field=models.URLField(max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
