# Generated by Django 3.0.3 on 2021-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0006_curatedarticle_website_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatedarticle',
            options={'ordering': ('-created_at',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='curatedarticle',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='curatedarticle',
            name='created',
        ),
        migrations.RemoveField(
            model_name='curatedarticle',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='curatedarticle',
            name='picture',
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='is_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curatedarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
