# Generated by Django 3.0.3 on 2021-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_articles', '0007_auto_20210429_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedarticle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Intro'),
        ),
    ]
