# Generated by Django 3.0.3 on 2022-10-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_auth', '0002_phoneotp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='is_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='successful_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhoneOtpMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_successful_at', models.DateTimeField(auto_now_add=True, help_text='Datetime of the last successful OTP.', verbose_name='Last OTP successful at')),
                ('generated_since', models.PositiveIntegerField(default=0, help_text='OTPs generated since last successful OTP.', verbose_name='Generated since last successful OTP')),
                ('notify_at', models.PositiveIntegerField(default=10, verbose_name='Notify after X failed attempts')),
                ('last_successful', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crater_auth.PhoneOtp', verbose_name='Last successful OPT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
