# Generated by Django 3.0.3 on 2021-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
