# Generated by Django 3.0.3 on 2021-12-29 10:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0002_reward_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='reward',
            name='title',
            field=models.CharField(blank=True, help_text='Short Title for the Reward', max_length=64, null=True),
        ),
    ]
