# Generated by Django 3.0.3 on 2021-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0003_auto_20211229_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
