# Generated by Django 3.0.3 on 2022-01-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0004_auto_20211229_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-order']},
        ),
    ]
