# Generated by Django 3.0.3 on 2022-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0005_auto_20220104_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
