# Generated by Django 3.0.3 on 2022-02-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0005_auto_20220104_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='number_of_coins',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='remaining_quantity',
        ),
    ]
