# Generated by Django 3.0.3 on 2022-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0006_auto_20220225_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='number_of_coins',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='reward',
            name='card_background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
