# Generated by Django 3.0.3 on 2022-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_rewards', '0007_auto_20220301_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardtype',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='rewardtype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
