# Generated by Django 3.0.3 on 2020-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wn_analytics', '0003_usersource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersource',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usersource',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
