# Generated by Django 3.0.3 on 2022-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wn_analytics', '0004_auto_20200911_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
