# Generated by Django 3.0.3 on 2022-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wn_analytics', '0005_usersource_utm_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='referrer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
