# Generated by Django 3.0.3 on 2022-02-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wn_analytics', '0006_usersource_referrer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersource',
            name='referrer_id',
        ),
        migrations.AddField(
            model_name='usersource',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
