# Generated by Django 3.0.3 on 2021-04-29 11:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('headings', models.CharField(max_length=64, verbose_name='Notification Heading')),
                ('contents', models.CharField(max_length=256, verbose_name='Notification Message')),
                ('small_icon', models.CharField(default='ic_notification', max_length=16, verbose_name='Small Notification Icon')),
                ('large_icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='Large Notification Icon')),
                ('android_accent_color', models.CharField(default='FF283845', max_length=16, verbose_name='Accent Color(Android only)')),
                ('buttons', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Custom Buttons for Notifications')),
                ('obj_type', models.CharField(choices=[('upcoming_meeting', 'Upcoming_Meeting'), ('conversation', 'Conversation'), ('create_conversation', 'Create_Conversation')], max_length=32, verbose_name='Client Object Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notification_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms_notifications.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
