# Generated by Django 3.0.3 on 2021-04-29 10:39

from django.db import migrations

from communications.notifications import constants

NOTIFICATION_CONTENT = (
    ("conversation_reminder", "Meeting Reminder", "Upcoming discussion @{time} about {topic}", constants.OBJECT_TYPE_UPCOMING_MEETING),
    ("conversation_live", "Your Meeting has started", "Click to join your conversation", constants.OBJECT_TYPE_CONVERSATION),
    ("conversation_created", "Your meeting has been set up", "Your meeting has been set up for {time} on {day}. Click to view details", constants.OBJECT_TYPE_CREATE_CONVERSATION),
    ("optin", "Opt-in for next week?", "Opt-in to get matched for a conversation with relevant people", constants.OBJECT_TYPE_UPCOMING_MEETING)
)


def create_notification_objects(apps, schema_editor):
    notification = apps.get_model("communications.notifications", "Notification")
    all_notifications = []

    for notification_content in NOTIFICATION_CONTENT:
        all_notifications.append(notification(
            name=notification_content[0],
            headings=notification_content[1],
            contents=notification_content[2],
            obj_type=notification_content[3]
        ))

    notification.objects.bulk_create(all_notifications)


class Migration(migrations.Migration):

    dependencies = [
        ('communications.notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_notification_objects),
    ]
