# Generated by Django 3.0.3 on 2021-05-17 11:53

from django.db import migrations
from communications.notifications import constants


def create_notification_objects(apps, schema_editor):
    notification = apps.get_model("comms_notifications", "Notification")
    all_notifications = []

    notification.objects.create(
        name=constants.GROUP_CONVERSATION_INVITE,
        headings="Join a conversation @{time} on {topic}",
        contents="Hosted by {first_name} - {new_tag} with {years_of_experience} experience",
        obj_type=constants.OBJECT_TYPE_CONVERSATION
    )


class Migration(migrations.Migration):

    dependencies = [
        ('comms_notifications', '0003_notificationlogs_data'),
    ]

    operations = [
        migrations.RunPython(create_notification_objects),
    ]
