# Generated by Django 3.0.3 on 2022-09-26 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms_notifications', '0004_auto_20210517_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationLogs',
            new_name='NotificationLog',
        ),
        migrations.AlterField(
            model_name='notification',
            name='contents',
            field=models.CharField(help_text='240 for Android, 178 (Heading + content) for iOS.', max_length=240, verbose_name='Notification Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='headings',
            field=models.CharField(help_text='65 for Android, 178 (Heading + content) for iOS.', max_length=65, verbose_name='Notification Heading'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='obj_type',
            field=models.CharField(choices=[('upcoming_meeting', 'Upcoming_Meeting'), ('conversation', 'Conversation'), ('create_conversation', 'Create_Conversation'), ('stream', 'Stream'), ('creator', 'Creator')], max_length=32, verbose_name='Client Object Type'),
        ),
    ]
