# Generated by Django 3.0.3 on 2022-09-26 11:30

from django.db import migrations

from communications.notifications import constants

NOTIFICATION_CONTENT = (
    (
        "stream_reminder_follower",
        "{creator_name} is LIVE right now! 📺",
        "If {topic_name} sounds interesting, join in now!",
        constants.OBJECT_TYPE_STREAM
    ),
    (
        "stream_reminder_attendee",
        "The stream you have been waiting for is live now! 📺",
        "You wanted to watch {topic_name} & now you don't have to wait any longer",
        constants.OBJECT_TYPE_STREAM
    ),
    (
        "stream_going_live_first (4PM & 12PM)",
        "What our team recommends watching this afternoon! 📺",
        "{topic_name} is a stream that we think you will not want to miss out on.",
        constants.OBJECT_TYPE_STREAM
    ),
    (
        "stream_going_live_second (6PM & 2PM)",
        "The most trending stream today! 📺",
        "{creator_name} channel seems to have some hype. Want to check it out?",
        constants.OBJET_TYPE_CREATOR
    ),
    (
        "stream_going_live_third (8PM & 4PM)",
        "Tune in for your evening dose of daily learning!! 📺",
        "Check out the live streams right now & discover something new.",
        constants.OBJECT_TYPE_STREAM
    ),
)


def create_notification_objects(apps, schema_editor):
    notification = apps.get_model("comms_notifications", "Notification")
    all_notifications = []

    for notification_content in NOTIFICATION_CONTENT:
        all_notifications.append(notification(
            name=notification_content[0],
            headings=notification_content[1],
            contents=notification_content[2],
            obj_type=notification_content[3]
        ))

    notification.objects.bulk_create(all_notifications)


class Migration(migrations.Migration):

    dependencies = [
        ('comms_notifications', '0005_auto_20220926_1707'),
    ]

    operations = [
        migrations.RunPython(create_notification_objects),
    ]
