# Generated by Django 3.0.3 on 2022-02-24 18:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_payments', '0002_auto_20220224_2346'),
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='intent_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_intent', to='crater_payments.Payment'),
        ),
        migrations.CreateModel(
            name='PaymentCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('charge_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_captured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captured', models.BooleanField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='stripe_payments.PaymentIntent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
