# Generated by Django 3.0.3 on 2022-01-13 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crater_payments', '0002_auto_20220113_1247'),
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(default=122, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_intent', to='crater_payments.Payment'),
            preserve_default=False,
        ),
    ]
