# Generated by Django 3.0.3 on 2022-01-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0002_auto_20220113_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='intent_id',
            field=models.CharField(default='asdasd', max_length=128),
            preserve_default=False,
        ),
    ]
