# Generated by Django 3.0.3 on 2022-01-17 12:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0003_paymentintent_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('charge_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_captured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captured', models.BooleanField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='stripe_payments.PaymentIntent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
