# Generated by Django 3.0.3 on 2020-11-18 15:11

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('max_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1)], verbose_name='Max Price')),
                ('max_discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1)], verbose_name='Max Discount')),
                ('max_discount_points', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Points for Max Discount')),
                ('title', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=800, verbose_name='Short Description')),
                ('list_image', models.ImageField(upload_to='', verbose_name='List Image')),
                ('cover_image', models.ImageField(upload_to='', verbose_name='Cover Image')),
                ('color', colorfield.fields.ColorField(default='#FFAC3B', max_length=18)),
                ('long_desc', models.TextField(verbose_name='Long Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('is_dark', models.BooleanField(default=True, verbose_name='Dark Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('point_applied', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)], verbose_name='Point Applied')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=255, verbose_name='Request Status')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rewards.Package', verbose_name='Package')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=800, verbose_name='Description')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_provide', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='rewards.PackageProvider', verbose_name='Package Provider'),
        ),
    ]
