# Generated by Django 3.0.3 on 2020-11-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='show_on_web',
            field=models.BooleanField(default=False, verbose_name='Show on Web'),
        ),
    ]
