# Generated by Django 3.0.3 on 2020-11-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_package_show_on_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
